require("dotenv").config();

const mongoose = require("mongoose");
const connectDB = require("../config/db");

const Location = require("../models/Location");
const Npc = require("../models/Npc");

const REGION_ID = "region_hoshimori";
const CITY_ID = "city_hoshimori";

function open(open, close, dayType = "normal") {
  return { dayType, open, close };
}

function r(timeStart, timeEnd, locationId, task) {
  return { dayType: "normal", timeStart, timeEnd, locationId, task };
}

const locations = [
  {
    locationId: "loc_hoshimori_grulla_azul",
    name: "La Grulla Azul",
    type: "inn",
    services: { food: true, lodging: true, work: true, rumors: true },
    openHours: [open("05:30", "22:30")],
    dangerLevel: "safe",
    visibleNpcIds: [],
    probableNpcIds: ["npc_roberto_valen", "npc_fern", "npc_yara_mils", "npc_joren_pell"],
    tags: ["hoshimori", "inn", "social", "work"],
  },
  {
    locationId: "loc_hoshimori_grulla_azul_comedor",
    name: "La Grulla Azul - sala baja/comedor",
    type: "inn_room",
    parentLocationId: "loc_hoshimori_grulla_azul",
    services: { food: true, social: true, work: true },
    openHours: [open("05:30", "22:30")],
    dangerLevel: "safe",
    visibleNpcIds: ["npc_roberto_valen"],
    probableNpcIds: ["npc_yara_mils", "npc_fern", "npc_joren_pell"],
    tags: ["hoshimori", "inn", "dining_room", "social"],
  },
  {
    locationId: "loc_hoshimori_grulla_azul_cocina",
    name: "La Grulla Azul - cocina",
    type: "kitchen",
    parentLocationId: "loc_hoshimori_grulla_azul",
    services: { cooking: true, staffOnly: true, foodPrep: true },
    openHours: [open("05:00", "21:30")],
    dangerLevel: "safe",
    visibleNpcIds: ["npc_yara_mils"],
    probableNpcIds: ["npc_fern", "npc_roberto_valen"],
    tags: ["hoshimori", "inn", "kitchen", "staff_area"],
  },
  {
    locationId: "loc_hoshimori_lucas_room",
    name: "Habitacion de Lucas",
    type: "inn_room",
    parentLocationId: "loc_hoshimori_grulla_azul",
    services: { rest: true, storage: true, privacy: true },
    dangerLevel: "safe",
    visibleNpcIds: [],
    probableNpcIds: [],
    tags: ["hoshimori", "inn", "lucas", "private_room", "rest"],
  },
  {
    locationId: "loc_hoshimori_grulla_azul_entrance_stable",
    name: "Entrada y establo pequeno de La Grulla Azul",
    type: "inn_entrance",
    parentLocationId: "loc_hoshimori_grulla_azul",
    services: { arrivals: true, smallStable: true, loading: true },
    dangerLevel: "safe",
    visibleNpcIds: [],
    probableNpcIds: ["npc_tessa", "npc_brann", "npc_joren_pell"],
    tags: ["hoshimori", "inn", "entrance", "stable", "supplies"],
  },
  {
    locationId: "loc_hoshimori_plaza",
    name: "Plaza de Hoshimori",
    type: "plaza",
    services: { publicGathering: true, notices: true, directions: true },
    dangerLevel: "safe",
    visibleNpcIds: ["npc_kael", "npc_celia_dorn", "npc_nia"],
    probableNpcIds: ["npc_irma", "npc_doran", "npc_rulan_veck"],
    tags: ["hoshimori", "plaza", "public", "social"],
  },
  {
    locationId: "loc_hoshimori_market",
    name: "Mercado de Hoshimori",
    type: "market",
    services: { commerce: true, rumors: true, food: true, supplies: true },
    openHours: [open("06:00", "18:00")],
    dangerLevel: "safe",
    visibleNpcIds: ["npc_pavo", "npc_sella", "npc_liora", "npc_irma", "npc_hilda_fen"],
    probableNpcIds: ["npc_tessa", "npc_merek_sol", "npc_brann", "npc_joren_pell"],
    tags: ["hoshimori", "market", "commerce", "rumors"],
  },
  {
    locationId: "loc_hoshimori_guild",
    name: "Gremio local de Hoshimori",
    type: "guild",
    services: { missions: true, reports: true, training: true, records: true },
    openHours: [open("07:00", "18:00")],
    dangerLevel: "safe",
    visibleNpcIds: ["npc_garrick_thorne", "npc_mara_vell"],
    probableNpcIds: ["npc_eddan_rusk", "npc_sael_nyra"],
    tags: ["hoshimori", "guild", "missions", "records"],
  },
  {
    locationId: "loc_hoshimori_guild_patio",
    name: "Patio del gremio",
    type: "training_yard",
    parentLocationId: "loc_hoshimori_guild",
    services: { training: true, evaluation: true, sparring: true },
    openHours: [open("07:00", "18:00")],
    dangerLevel: "low",
    visibleNpcIds: ["npc_eddan_rusk"],
    probableNpcIds: ["npc_garrick_thorne", "npc_sael_nyra"],
    tags: ["hoshimori", "guild", "training", "yard"],
  },
  {
    locationId: "loc_hoshimori_temple_serene_flame",
    name: "Templo de la Llama Serena",
    type: "temple",
    services: { advice: true, firstAid: true, rest: true, prayer: true },
    openHours: [open("06:00", "20:00")],
    dangerLevel: "safe",
    visibleNpcIds: ["npc_narek"],
    probableNpcIds: ["npc_maelis"],
    tags: ["hoshimori", "temple", "serene_flame", "first_aid"],
  },
  {
    locationId: "loc_hoshimori_borin_smithy",
    name: "Herreria de Borin",
    type: "smithy",
    parentLocationId: "loc_hoshimori_market",
    ownerNpcId: "npc_borin",
    services: { buy: true, sell: true, repair: true, tools: true, weapons: true },
    openHours: [open("07:00", "18:00")],
    dangerLevel: "safe",
    visibleNpcIds: ["npc_borin"],
    probableNpcIds: [],
    tags: ["hoshimori", "smithy", "tools", "weapons", "repair"],
  },
  {
    locationId: "loc_hoshimori_sella_workshop",
    name: "Taller de Sella",
    type: "tailor_workshop",
    parentLocationId: "loc_hoshimori_market",
    ownerNpcId: "npc_sella",
    services: { tailoring: true, clothing: true, repair: true },
    openHours: [open("07:00", "18:00")],
    dangerLevel: "safe",
    visibleNpcIds: ["npc_sella"],
    probableNpcIds: ["npc_irma"],
    tags: ["hoshimori", "tailor", "clothing", "repair"],
  },
  {
    locationId: "loc_hoshimori_liora_stall",
    name: "Puesto de Liora",
    type: "herbalist_stall",
    parentLocationId: "loc_hoshimori_market",
    ownerNpcId: "npc_liora",
    services: { herbs: true, medicine: true, advice: true },
    openHours: [open("07:00", "17:30")],
    dangerLevel: "safe",
    visibleNpcIds: ["npc_liora"],
    probableNpcIds: ["npc_maelis"],
    tags: ["hoshimori", "herbalist", "medicine", "market"],
  },
  {
    locationId: "loc_hoshimori_road_to_mill",
    name: "Camino del Molino",
    type: "road",
    services: { travel: true, carts: true },
    dangerLevel: "low",
    visibleNpcIds: [],
    probableNpcIds: ["npc_tessa", "npc_oren", "npc_doran"],
    tags: ["hoshimori", "road", "mill", "travel"],
  },
  {
    locationId: "loc_hoshimori_mill",
    name: "Molino de Oren",
    type: "mill",
    ownerNpcId: "npc_oren",
    services: { milling: true, grain: true, localWork: true },
    openHours: [open("06:00", "18:00")],
    dangerLevel: "safe",
    visibleNpcIds: ["npc_oren"],
    probableNpcIds: ["npc_tessa", "npc_doran"],
    tags: ["hoshimori", "mill", "grain", "work"],
  },
  {
    locationId: "loc_hoshimori_forest_whispers_edge",
    name: "Bosque de los Susurros - borde",
    type: "forest_edge",
    services: { foraging: true, travel: true },
    dangerLevel: "low",
    visibleNpcIds: [],
    probableNpcIds: ["npc_doran"],
    tags: ["hoshimori", "forest", "whispers", "edge", "foraging"],
  },
  {
    locationId: "loc_hoshimori_forest_whispers_mid",
    name: "Bosque de los Susurros - zona media",
    type: "forest",
    services: { foraging: true, hunting: true },
    dangerLevel: "medium",
    visibleNpcIds: [],
    probableNpcIds: [],
    tags: ["hoshimori", "forest", "whispers", "danger"],
  },
  {
    locationId: "loc_hoshimori_forest_whispers_deep",
    name: "Bosque de los Susurros - profundidad",
    type: "deep_forest",
    services: { exploration: true },
    dangerLevel: "high",
    visibleNpcIds: [],
    probableNpcIds: [],
    tags: ["hoshimori", "forest", "whispers", "deep", "danger"],
  },
  {
    locationId: "loc_hoshimori_gray_hills_base",
    name: "Colinas Grises - base",
    type: "hills",
    services: { travel: true, gathering: true },
    dangerLevel: "medium",
    visibleNpcIds: [],
    probableNpcIds: [],
    tags: ["hoshimori", "gray_hills", "travel", "danger"],
  },
  {
    locationId: "loc_hoshimori_gray_hills_caves",
    name: "Cuevas menores de Colinas Grises",
    type: "caves",
    parentLocationId: "loc_hoshimori_gray_hills_base",
    services: { exploration: true, mining: false },
    dangerLevel: "high",
    visibleNpcIds: [],
    probableNpcIds: [],
    tags: ["hoshimori", "gray_hills", "caves", "danger"],
  },
  {
    locationId: "loc_hoshimori_bakery",
    name: "Panaderia de Hilda",
    type: "bakery",
    parentLocationId: "loc_hoshimori_market",
    ownerNpcId: "npc_hilda_fen",
    services: { food: true, bread: true, gossip: true },
    openHours: [open("05:30", "16:00")],
    dangerLevel: "safe",
    visibleNpcIds: ["npc_hilda_fen"],
    probableNpcIds: ["npc_irma"],
    tags: ["hoshimori", "bakery", "food", "market"],
  },
  {
    locationId: "loc_hoshimori_guard_post",
    name: "Puesto de guardia local",
    type: "guard_post",
    services: { law: true, reports: true, publicOrder: true },
    openHours: [open("00:00", "23:59")],
    dangerLevel: "safe",
    visibleNpcIds: ["npc_kael", "npc_rulan_veck"],
    probableNpcIds: [],
    tags: ["hoshimori", "guard", "law", "order"],
  },
  {
    locationId: "loc_hoshimori_council_records",
    name: "Sala de registros del consejo",
    type: "council_records",
    services: { records: true, permits: true, localCouncil: true },
    openHours: [open("08:00", "16:00")],
    dangerLevel: "safe",
    visibleNpcIds: ["npc_celia_dorn"],
    probableNpcIds: [],
    tags: ["hoshimori", "council", "records", "bureaucracy"],
  },
  {
    locationId: "loc_hoshimori_tannery",
    name: "Taller de curtidor y pieles",
    type: "tannery",
    parentLocationId: "loc_hoshimori_market",
    ownerNpcId: "npc_merek_sol",
    services: { hides: true, leather: true, processing: true },
    openHours: [open("07:00", "17:00")],
    dangerLevel: "safe",
    visibleNpcIds: ["npc_merek_sol"],
    probableNpcIds: [],
    tags: ["hoshimori", "tannery", "leather", "materials"],
  },
  {
    locationId: "loc_hoshimori_road_entrance",
    name: "Entrada del pueblo y camino principal",
    type: "road_entrance",
    services: { travel: true, carts: true, guardNotice: true },
    dangerLevel: "safe",
    visibleNpcIds: ["npc_tessa"],
    probableNpcIds: ["npc_kael", "npc_joren_pell"],
    tags: ["hoshimori", "entrance", "road", "travel"],
  },
];

const sharedDefaults = {
  regionId: REGION_ID,
  cityId: CITY_ID,
  persistenceLevel: "secondary",
  relationshipWithLucas: { trust: 0, affection: 0, suspicion: 0, respect: 0, fear: 0, jealousy: 0, notes: "" },
  factionLinks: [],
  secrets: [],
  knownPublicFacts: [],
  flags: {},
};

const npcs = [
  {
    npcId: "npc_roberto_valen",
    name: "Roberto Valen",
    age: 42,
    role: "dueno/encargado de La Grulla Azul",
    homeLocationId: "loc_hoshimori_grulla_azul",
    currentLocationId: "loc_hoshimori_grulla_azul_comedor",
    currentTask: "supervisando mediodia, sala y suministros",
    availability: { status: "available", reason: "visible en sala/comedor durante mediodia" },
    persistenceLevel: "important",
    personality: ["directo", "practico", "trabajador", "justo", "seco"],
    speechStyle: "frases cortas, tono seco, humor gastado",
    values: ["responsabilidad", "trabajo bien hecho", "palabra dada"],
    tolerates: ["errores honestos", "esfuerzo", "preguntas directas"],
    rejects: ["mentiras", "robo", "faltas graves", "excusas flojas"],
    relationshipWithLucas: {
      trust: 56,
      respect: 35,
      notes: "Confianza funcional. Lucas trabaja en La Grulla Azul y completo el turno manana Dia 10 con buen rendimiento.",
    },
    factionLinks: [{ factionId: "faction_grulla_azul", role: "encargado", loyalty: 85 }],
    knownPublicFacts: ["Lucas trabaja en La Grulla Azul."],
    routineBase: [
      r("05:30", "07:00", "loc_hoshimori_grulla_azul_cocina", "organizando cocina y desayuno"),
      r("07:00", "11:00", "loc_hoshimori_grulla_azul_comedor", "supervisando sala, proveedores y trabajo"),
      r("11:00", "14:00", "loc_hoshimori_grulla_azul_comedor", "supervisando mediodia, sala y suministros"),
      r("14:00", "20:30", "loc_hoshimori_grulla_azul_comedor", "supervisando turno tarde"),
      r("20:30", "22:30", "loc_hoshimori_grulla_azul_comedor", "cerrando servicio de noche"),
      r("22:30", "05:30", "loc_hoshimori_grulla_azul", "durmiendo o cerrando asuntos internos"),
    ],
  },
  {
    npcId: "npc_fern",
    name: "Fern",
    age: 15,
    role: "trabajadora reservada de La Grulla Azul; talento magico",
    homeLocationId: "loc_hoshimori_grulla_azul",
    currentLocationId: "loc_hoshimori_grulla_azul",
    currentTask: "tareas internas de mediodia",
    availability: { status: "busy", reason: "posible de paso por tareas de comedor" },
    persistenceLevel: "important",
    personality: ["reservada", "prudente", "observadora", "seria"],
    speechStyle: "breve, directa, a veces seca pero no cruel",
    values: ["discrecion", "control", "responsabilidad", "seguridad"],
    tolerates: ["respeto", "honestidad", "ayuda sin presion"],
    rejects: ["invasion", "insistencia", "magia imprudente"],
    relationshipWithLucas: {
      trust: 24,
      notes: "Trato basico-cordial. Sabe que Lucas desperto magia/mana porque el se lo conto.",
    },
    factionLinks: [{ factionId: "faction_grulla_azul", role: "trabajadora", loyalty: 65 }],
    knownPublicFacts: ["Trabaja en La Grulla Azul."],
    routineBase: [
      r("06:30", "12:00", "loc_hoshimori_grulla_azul", "tareas de posada"),
      r("12:00", "14:00", "loc_hoshimori_grulla_azul", "tareas internas de mediodia"),
      r("14:00", "20:30", "loc_hoshimori_grulla_azul", "apoyo en comedor y cocina"),
      r("20:30", "22:30", "loc_hoshimori_grulla_azul", "cierre menor de posada"),
      r("22:30", "06:30", "loc_hoshimori_grulla_azul", "durmiendo o descansando"),
    ],
  },
  {
    npcId: "npc_yara_mils",
    name: "Yara Mils",
    age: 16,
    role: "aprendiz/ayudante de cocina y posada",
    homeLocationId: "loc_hoshimori_grulla_azul",
    currentLocationId: "loc_hoshimori_grulla_azul_cocina",
    currentTask: "trabajo de cocina durante mediodia",
    availability: { status: "busy", reason: "audible/probable en cocina cercana" },
    persistenceLevel: "important",
    personality: ["amable", "nerviosa", "trabajadora", "timida", "un poco celosa si siente apego o inseguridad"],
    speechStyle: "suave, frases cortas cuando se siente observada",
    values: ["sentirse util", "no ser humillada", "que respeten su esfuerzo"],
    tolerates: ["bromas ligeras", "ayuda genuina", "compania tranquila"],
    rejects: ["presion", "burla publica", "coqueteo brusco", "comparaciones crueles"],
    relationshipWithLucas: {
      trust: 15,
      jealousy: 5,
      notes: "Trato amable inicial. Yara ve a Lucas como amable, trabajador, tranquilo y agradable.",
    },
    factionLinks: [{ factionId: "faction_grulla_azul", role: "ayudante", loyalty: 60 }],
    knownPublicFacts: ["Trabaja en la cocina de La Grulla Azul."],
    routineBase: [
      r("06:00", "12:00", "loc_hoshimori_grulla_azul_cocina", "trabajo de cocina y preparacion"),
      r("12:00", "14:00", "loc_hoshimori_grulla_azul_cocina", "trabajo de cocina durante mediodia"),
      r("14:00", "20:30", "loc_hoshimori_grulla_azul_cocina", "apoyo de cocina y servicio"),
      r("20:30", "21:30", "loc_hoshimori_grulla_azul_cocina", "cierre de cocina"),
      r("21:30", "06:00", "loc_hoshimori_grulla_azul", "descansando o durmiendo"),
    ],
  },
  {
    npcId: "npc_garrick_thorne",
    name: "Garrick Thorne",
    age: 38,
    role: "coordinador de voluntarios/contacto del gremio",
    homeLocationId: "loc_hoshimori_guild",
    currentLocationId: "loc_hoshimori_guild",
    currentTask: "revisando reportes de mediodia",
    availability: { status: "available", reason: "normalmente disponible en el gremio" },
    persistenceLevel: "important",
    personality: ["firme", "razonable", "institucional", "protector de novatos"],
    speechStyle: "claro, serio, con advertencias practicas",
    values: ["reportes honestos", "preparacion", "responsabilidad"],
    tolerates: ["preguntas claras", "cautela", "disciplina"],
    rejects: ["exageraciones", "imprudencia", "mentiras en mision"],
    relationshipWithLucas: {
      trust: 36,
      respect: 25,
      notes: "Trato cordial/institucional. Lucas completo voluntariado del Bosque de los Susurros.",
    },
    factionLinks: [{ factionId: "faction_hoshimori_guild", role: "coordinador", loyalty: 80 }],
    knownPublicFacts: ["Coordina encargos y voluntarios del gremio local."],
    routineBase: [
      r("07:00", "12:00", "loc_hoshimori_guild", "coordinando registros y voluntarios"),
      r("12:00", "14:00", "loc_hoshimori_guild", "revisando reportes de mediodia"),
      r("14:00", "18:00", "loc_hoshimori_guild", "coordinando encargos y rutas"),
      r("18:00", "22:00", "loc_hoshimori_guild", "cerrando reportes del gremio"),
      r("22:00", "07:00", "loc_hoshimori_guild", "fuera de atencion publica"),
    ],
  },
  {
    npcId: "npc_mara_vell",
    name: "Mara Vell",
    age: 31,
    role: "administradora/escribana del gremio",
    homeLocationId: "loc_hoshimori_guild",
    currentLocationId: "loc_hoshimori_guild",
    currentTask: "gestionando registros y cartelera",
    availability: { status: "available", reason: "normalmente en mostrador/archivos del gremio" },
    persistenceLevel: "important",
    personality: ["ordenada", "precisa", "algo fria", "justa con procedimientos"],
    speechStyle: "formal, seca, muy concreta",
    values: ["registros", "pruebas", "puntualidad", "claridad"],
    tolerates: ["formularios completos", "respeto por turnos"],
    rejects: ["papeles incompletos", "excusas", "gente que toca archivos"],
    factionLinks: [{ factionId: "faction_hoshimori_guild", role: "escribana", loyalty: 75 }],
    routineBase: [
      r("07:00", "12:00", "loc_hoshimori_guild", "gestionando registros y cartelera"),
      r("12:00", "14:00", "loc_hoshimori_guild", "organizando reportes de mediodia"),
      r("14:00", "18:00", "loc_hoshimori_guild", "atendiendo registros y pruebas"),
      r("18:00", "21:00", "loc_hoshimori_guild", "cerrando archivos"),
      r("21:00", "07:00", "loc_hoshimori_guild", "fuera de atencion publica"),
    ],
  },
  {
    npcId: "npc_eddan_rusk",
    name: "Eddan Rusk",
    age: 45,
    role: "instructor/evaluador fisico del gremio",
    homeLocationId: "loc_hoshimori_guild_patio",
    currentLocationId: "loc_hoshimori_guild_patio",
    currentTask: "supervisando patio o equipo del gremio",
    availability: { status: "busy", reason: "ocupado con evaluaciones o mantenimiento" },
    persistenceLevel: "important",
    personality: ["exigente", "frontal", "veterano cansado", "justo"],
    speechStyle: "aspero, sin adornos",
    values: ["tecnica", "disciplina", "retirada inteligente"],
    tolerates: ["esfuerzo real", "preguntas utiles"],
    rejects: ["fanfarroneria", "ataques sin plan", "novatos suicidas"],
    factionLinks: [{ factionId: "faction_hoshimori_guild", role: "instructor", loyalty: 70 }],
    routineBase: [
      r("07:00", "12:00", "loc_hoshimori_guild_patio", "supervisando entrenamiento y equipo"),
      r("12:00", "14:00", "loc_hoshimori_guild_patio", "descanso y revision de equipo"),
      r("14:00", "18:00", "loc_hoshimori_guild_patio", "evaluando novatos"),
      r("18:00", "21:00", "loc_hoshimori_guild", "cerrando asuntos del gremio"),
      r("21:00", "07:00", "loc_hoshimori_guild_patio", "descansando o vigilando equipo"),
    ],
  },
  {
    npcId: "npc_brann",
    name: "Brann",
    age: 18,
    role: "ayudante ocasional de carga/mozo temporal",
    homeLocationId: "loc_hoshimori_grulla_azul",
    currentLocationId: "loc_hoshimori_market",
    currentTask: "buscando trabajo o haciendo encargos menores",
    availability: { status: "unknown", reason: "se mueve entre posada, mercado y gremio" },
    personality: ["ruidoso", "competitivo", "algo inseguro bajo bromas"],
    speechStyle: "bromista, provocador suave",
    values: ["fuerza", "reconocimiento", "paga rapida"],
    tolerates: ["competencia sana", "trabajo simple"],
    rejects: ["ser humillado frente a otros"],
    routineBase: [
      r("06:00", "12:00", "loc_hoshimori_market", "buscando trabajos de carga"),
      r("12:00", "14:00", "loc_hoshimori_market", "haciendo encargos menores"),
      r("14:00", "18:00", "loc_hoshimori_grulla_azul_entrance_stable", "ayudando con carga o esperando paga"),
      r("18:00", "22:00", "loc_hoshimori_grulla_azul", "buscando comida y charla"),
      r("22:00", "06:00", "loc_hoshimori_grulla_azul", "descansando"),
    ],
  },
  {
    npcId: "npc_pavo",
    name: "Pavo",
    age: 50,
    role: "vendedor de alimentos/raciones",
    homeLocationId: "loc_hoshimori_market",
    currentLocationId: "loc_hoshimori_market",
    currentTask: "vendiendo comida de mediodia",
    availability: { status: "available", reason: "atiende su puesto en el mercado durante el dia" },
    personality: ["charlatan", "negociador", "atento a rumores"],
    speechStyle: "rapido, vendedor, exagera sin mentir del todo",
    values: ["clientes", "margen", "informacion"],
    tolerates: ["regateo razonable", "clientes curiosos"],
    rejects: ["regateo agresivo", "deuda sin garantia"],
    routineBase: [
      r("06:00", "12:00", "loc_hoshimori_market", "atendiendo puesto de raciones"),
      r("12:00", "14:00", "loc_hoshimori_market", "vendiendo comida de mediodia"),
      r("14:00", "18:00", "loc_hoshimori_market", "atendiendo clientes del mercado"),
      r("18:00", "20:00", "loc_hoshimori_market", "cerrando puesto"),
      r("20:00", "06:00", "loc_hoshimori_market", "fuera de atencion publica"),
    ],
  },
  {
    npcId: "npc_borin",
    name: "Borin",
    age: 47,
    role: "herrero",
    homeLocationId: "loc_hoshimori_borin_smithy",
    currentLocationId: "loc_hoshimori_borin_smithy",
    currentTask: "descanso y reparaciones menores",
    availability: { status: "available", reason: "normalmente disponible en la herreria si esta operativa" },
    personality: ["grunon", "metodico", "orgulloso del oficio"],
    speechStyle: "pocas palabras, metaforas de metal",
    values: ["buen pago", "herramientas cuidadas", "respeto por el oficio"],
    tolerates: ["preguntas tecnicas", "pagos justos"],
    rejects: ["tocar herramientas sin permiso", "pedir armas fiadas"],
    routineBase: [
      r("07:00", "12:00", "loc_hoshimori_borin_smithy", "trabajando en la herreria"),
      r("12:00", "14:00", "loc_hoshimori_borin_smithy", "descanso y reparaciones menores"),
      r("14:00", "18:00", "loc_hoshimori_borin_smithy", "atendiendo herreria"),
      r("18:00", "21:00", "loc_hoshimori_borin_smithy", "cerrando herramientas"),
      r("21:00", "07:00", "loc_hoshimori_borin_smithy", "fuera de atencion publica"),
    ],
  },
  {
    npcId: "npc_sella",
    name: "Sella",
    age: 34,
    role: "costurera/tendera de telas",
    homeLocationId: "loc_hoshimori_sella_workshop",
    currentLocationId: "loc_hoshimori_sella_workshop",
    currentTask: "trabajando en arreglos y telas",
    availability: { status: "available", reason: "suele estar en su taller del mercado" },
    personality: ["observadora", "paciente", "chismosa moderada"],
    speechStyle: "amable pero precisa",
    values: ["presentacion", "cuidado", "discrecion rentable"],
    tolerates: ["clientes pacientes", "arreglos pequenos"],
    rejects: ["apuros groseros", "manchar telas"],
    routineBase: [
      r("07:00", "12:00", "loc_hoshimori_sella_workshop", "trabajando en arreglos y telas"),
      r("12:00", "14:00", "loc_hoshimori_sella_workshop", "atendiendo encargos tranquilos"),
      r("14:00", "18:00", "loc_hoshimori_sella_workshop", "cosiendo y vendiendo telas"),
      r("18:00", "21:00", "loc_hoshimori_market", "cerrando y escuchando rumores"),
      r("21:00", "07:00", "loc_hoshimori_sella_workshop", "descansando"),
    ],
  },
  {
    npcId: "npc_liora",
    name: "Liora",
    age: 29,
    role: "herborista",
    homeLocationId: "loc_hoshimori_liora_stall",
    currentLocationId: "loc_hoshimori_liora_stall",
    currentTask: "atendiendo puesto de hierbas",
    availability: { status: "available", reason: "normalmente disponible en el mercado" },
    personality: ["tranquila", "intuitiva", "algo misteriosa"],
    speechStyle: "pausado, con preguntas",
    values: ["calma", "salud", "plantas", "pago justo"],
    tolerates: ["preguntas honestas", "trueque razonable"],
    rejects: ["maltratar plantas", "exigir curas milagrosas"],
    routineBase: [
      r("07:00", "12:00", "loc_hoshimori_liora_stall", "preparando y vendiendo hierbas"),
      r("12:00", "14:00", "loc_hoshimori_liora_stall", "atendiendo consultas de mediodia"),
      r("14:00", "17:30", "loc_hoshimori_liora_stall", "vendiendo remedios simples"),
      r("17:30", "21:00", "loc_hoshimori_temple_serene_flame", "consultando hierbas con el templo"),
      r("21:00", "07:00", "loc_hoshimori_liora_stall", "descansando"),
    ],
  },
  {
    npcId: "npc_narek",
    name: "Narek",
    age: 52,
    role: "cuidador del Templo de la Llama Serena",
    homeLocationId: "loc_hoshimori_temple_serene_flame",
    currentLocationId: "loc_hoshimori_temple_serene_flame",
    currentTask: "atendiendo visitas tranquilas",
    availability: { status: "available", reason: "suele estar en el templo" },
    personality: ["sereno", "compasivo", "firme ante mentiras graves"],
    speechStyle: "bajo, pausado, reflexivo",
    values: ["memoria", "calma", "promesas", "duelo"],
    tolerates: ["silencio", "preguntas sinceras"],
    rejects: ["mentiras graves", "violencia en el templo"],
    factionLinks: [{ factionId: "faction_hoshimori_temple", role: "cuidador", loyalty: 75 }],
    routineBase: [
      r("06:00", "12:00", "loc_hoshimori_temple_serene_flame", "cuidando el templo"),
      r("12:00", "14:00", "loc_hoshimori_temple_serene_flame", "atendiendo visitas tranquilas"),
      r("14:00", "20:00", "loc_hoshimori_temple_serene_flame", "velas, consejo y primeros auxilios"),
      r("20:00", "22:00", "loc_hoshimori_temple_serene_flame", "cierre del templo"),
      r("22:00", "06:00", "loc_hoshimori_temple_serene_flame", "descansando"),
    ],
  },
  {
    npcId: "npc_kael",
    name: "Kael",
    age: 36,
    role: "guardia visible de Hoshimori",
    homeLocationId: "loc_hoshimori_guard_post",
    currentLocationId: "loc_hoshimori_plaza",
    currentTask: "vigilando plaza y mercado",
    availability: { status: "busy", reason: "en patrulla de orden publico" },
    personality: ["cansado", "pragmatico", "protector del orden"],
    speechStyle: "directo, con tono de advertencia",
    values: ["no crear panico", "resolver conflictos sin escalar"],
    tolerates: ["reportes claros", "cooperacion"],
    rejects: ["peleas publicas", "amenazas", "robos"],
    factionLinks: [{ factionId: "faction_hoshimori_guard", role: "guardia", loyalty: 70 }],
    routineBase: [
      r("06:00", "12:00", "loc_hoshimori_plaza", "vigilando plaza y mercado"),
      r("12:00", "14:00", "loc_hoshimori_plaza", "patrulla de mediodia"),
      r("14:00", "18:00", "loc_hoshimori_market", "vigilando mercado"),
      r("18:00", "22:00", "loc_hoshimori_guard_post", "registrando novedades"),
      r("22:00", "06:00", "loc_hoshimori_guard_post", "guardia nocturna rotativa"),
    ],
  },
  {
    npcId: "npc_celia_dorn",
    name: "Celia Dorn",
    age: 40,
    role: "escribana del consejo local",
    homeLocationId: "loc_hoshimori_council_records",
    currentLocationId: "loc_hoshimori_council_records",
    currentTask: "gestionando registros locales",
    availability: { status: "busy", reason: "ocupada con registros y acuerdos" },
    personality: ["formal", "diplomatica", "cuidadosa"],
    speechStyle: "educada, burocratica",
    values: ["documentos", "acuerdos", "reputacion del pueblo"],
    tolerates: ["procedimientos", "solicitudes correctas"],
    rejects: ["desorden documental", "presion politica brusca"],
    factionLinks: [{ factionId: "faction_hoshimori_council", role: "escribana", loyalty: 75 }],
    routineBase: [
      r("08:00", "12:00", "loc_hoshimori_council_records", "gestionando registros locales"),
      r("12:00", "14:00", "loc_hoshimori_council_records", "ordenando acuerdos de mediodia"),
      r("14:00", "16:00", "loc_hoshimori_council_records", "atendiendo tramites"),
      r("16:00", "20:00", "loc_hoshimori_plaza", "tratando asuntos publicos menores"),
      r("20:00", "08:00", "loc_hoshimori_council_records", "fuera de atencion publica"),
    ],
  },
  {
    npcId: "npc_irma",
    name: "Irma",
    age: 63,
    role: "vecina/vendedora ocasional/historiadora oral",
    homeLocationId: "loc_hoshimori_plaza",
    currentLocationId: "loc_hoshimori_market",
    currentTask: "conversando y observando el mercado",
    availability: { status: "available", reason: "suele moverse entre mercado, templo y plaza" },
    personality: ["curiosa", "dramatica", "afectuosa si cae bien"],
    speechStyle: "cuenta historias, mezcla rumor y recuerdo",
    values: ["memoria", "juventud respetuosa", "pan caliente"],
    tolerates: ["charla", "respeto a mayores"],
    rejects: ["groseria", "ignorar advertencias viejas"],
    routineBase: [
      r("06:00", "12:00", "loc_hoshimori_market", "conversando y observando el mercado"),
      r("12:00", "14:00", "loc_hoshimori_market", "buscando pan y charla de mediodia"),
      r("14:00", "18:00", "loc_hoshimori_plaza", "contando historias y escuchando noticias"),
      r("18:00", "21:00", "loc_hoshimori_temple_serene_flame", "visitando el templo"),
      r("21:00", "06:00", "loc_hoshimori_plaza", "descansando"),
    ],
  },
  {
    npcId: "npc_sael_nyra",
    name: "Sael Nyra",
    age: 19,
    role: "aventurera novata recurrente",
    homeLocationId: "loc_hoshimori_guild",
    currentLocationId: "loc_hoshimori_guild",
    currentTask: "buscando oportunidades en el gremio",
    availability: { status: "available", reason: "frecuenta el gremio y la posada" },
    personality: ["ambiciosa", "simpatica", "algo imprudente"],
    speechStyle: "energetica, vende bien sus logros",
    values: ["ascenso", "reconocimiento", "companeros utiles"],
    tolerates: ["competencia", "planes con recompensa"],
    rejects: ["ser tratada como inutil", "esperas largas"],
    factionLinks: [{ factionId: "faction_hoshimori_guild", role: "aventurera novata", loyalty: 45 }],
    routineBase: [
      r("07:00", "12:00", "loc_hoshimori_guild", "buscando oportunidades en el gremio"),
      r("12:00", "14:00", "loc_hoshimori_guild", "revisando cartelera de mediodia"),
      r("14:00", "18:00", "loc_hoshimori_guild_patio", "entrenando o presumiendo tecnica"),
      r("18:00", "22:00", "loc_hoshimori_grulla_azul", "cenando y buscando compania"),
      r("22:00", "07:00", "loc_hoshimori_guild", "descansando o fuera de escena"),
    ],
  },
  {
    npcId: "npc_oren",
    name: "Oren",
    age: 48,
    role: "molinero",
    homeLocationId: "loc_hoshimori_mill",
    currentLocationId: "loc_hoshimori_mill",
    currentTask: "trabajando en el molino",
    availability: { status: "busy", reason: "normalmente en el molino" },
    persistenceLevel: "background_prepared",
    personality: ["practico", "preocupado por rutas y clima"],
    speechStyle: "campesino directo",
    values: ["grano", "maquinaria", "familia", "seguridad de caminos"],
    tolerates: ["ayuda concreta", "herramientas cuidadas"],
    rejects: ["interrumpir maquinaria", "rumores que asustan proveedores"],
    routineBase: [
      r("06:00", "12:00", "loc_hoshimori_mill", "trabajando en el molino"),
      r("12:00", "14:00", "loc_hoshimori_mill", "revisando grano y descanso breve"),
      r("14:00", "18:00", "loc_hoshimori_mill", "manteniendo maquinaria"),
      r("18:00", "21:00", "loc_hoshimori_road_to_mill", "cerrando entregas del dia"),
      r("21:00", "06:00", "loc_hoshimori_mill", "descansando"),
    ],
  },
  {
    npcId: "npc_tessa",
    name: "Tessa",
    age: 27,
    role: "carretera/transportista local",
    homeLocationId: "loc_hoshimori_road_entrance",
    currentLocationId: "loc_hoshimori_road_entrance",
    currentTask: "revisando transporte y rutas",
    availability: { status: "unknown", reason: "se mueve entre entrada del pueblo, mercado y caminos" },
    persistenceLevel: "background_prepared",
    personality: ["franca", "resistente", "desconfiada con desconocidos"],
    speechStyle: "aspero, con humor seco",
    values: ["rutas seguras", "paga justa", "animales bien tratados"],
    tolerates: ["planes claros", "ayuda con carga"],
    rejects: ["mentiras de ruta", "maltratar animales"],
    routineBase: [
      r("06:00", "12:00", "loc_hoshimori_road_entrance", "revisando transporte y rutas"),
      r("12:00", "14:00", "loc_hoshimori_market", "cerrando tratos de transporte"),
      r("14:00", "18:00", "loc_hoshimori_road_to_mill", "moviendo carga o revisando camino"),
      r("18:00", "22:00", "loc_hoshimori_grulla_azul_entrance_stable", "cuidando carro y animales"),
      r("22:00", "06:00", "loc_hoshimori_road_entrance", "descansando"),
    ],
  },
  {
    npcId: "npc_hilda_fen",
    name: "Hilda Fen",
    age: 55,
    role: "panadera",
    homeLocationId: "loc_hoshimori_bakery",
    currentLocationId: "loc_hoshimori_bakery",
    currentTask: "vendiendo pan y revisando harina",
    availability: { status: "available", reason: "suele estar cerca del horno o mercado" },
    persistenceLevel: "background_prepared",
    personality: ["maternal con limites", "severa con deudores"],
    speechStyle: "calida hasta que la hacen enojar",
    values: ["pan fresco", "pago puntual", "familias alimentadas"],
    tolerates: ["ninos curiosos", "clientes humildes"],
    rejects: ["deudores abusivos", "desperdiciar comida"],
    routineBase: [
      r("05:00", "09:00", "loc_hoshimori_bakery", "horneando pan"),
      r("09:00", "12:00", "loc_hoshimori_market", "vendiendo pan en mercado"),
      r("12:00", "14:00", "loc_hoshimori_bakery", "revisando harina y ventas"),
      r("14:00", "16:00", "loc_hoshimori_bakery", "cerrando venta del dia"),
      r("16:00", "05:00", "loc_hoshimori_bakery", "descansando o preparando masa"),
    ],
  },
  {
    npcId: "npc_rulan_veck",
    name: "Rulan Veck",
    age: 22,
    role: "aprendiz de guardia",
    homeLocationId: "loc_hoshimori_guard_post",
    currentLocationId: "loc_hoshimori_guard_post",
    currentTask: "patrulla menor",
    availability: { status: "busy", reason: "en tareas de guardia" },
    persistenceLevel: "background_prepared",
    personality: ["correcto", "inseguro", "quiere demostrar valor"],
    speechStyle: "formal de mas",
    values: ["procedimiento", "ser tomado en serio"],
    tolerates: ["instrucciones claras", "entrenamiento"],
    rejects: ["burlas", "ordenes contradictorias"],
    factionLinks: [{ factionId: "faction_hoshimori_guard", role: "aprendiz", loyalty: 60 }],
    routineBase: [
      r("06:00", "12:00", "loc_hoshimori_guard_post", "patrulla menor"),
      r("12:00", "14:00", "loc_hoshimori_plaza", "apoyo de mediodia en plaza"),
      r("14:00", "18:00", "loc_hoshimori_guard_post", "entrenando y registrando novedades"),
      r("18:00", "22:00", "loc_hoshimori_plaza", "patrulla vespertina"),
      r("22:00", "06:00", "loc_hoshimori_guard_post", "descansando o guardia rotativa"),
    ],
  },
  {
    npcId: "npc_merek_sol",
    name: "Merek Sol",
    age: 44,
    role: "curtidor/pieles",
    homeLocationId: "loc_hoshimori_tannery",
    currentLocationId: "loc_hoshimori_tannery",
    currentTask: "revisando pieles y materiales",
    availability: { status: "busy", reason: "trabaja entre taller y mercado" },
    persistenceLevel: "background_prepared",
    personality: ["reservado", "honesto si le pagan"],
    speechStyle: "pocas palabras",
    values: ["material bueno", "trato justo", "silencio"],
    tolerates: ["negocios directos", "buenas pieles"],
    rejects: ["regateo abusivo", "material podrido vendido como bueno"],
    routineBase: [
      r("07:00", "12:00", "loc_hoshimori_tannery", "revisando pieles y materiales"),
      r("12:00", "14:00", "loc_hoshimori_tannery", "procesando encargos de mediodia"),
      r("14:00", "17:00", "loc_hoshimori_market", "negociando materiales"),
      r("17:00", "21:00", "loc_hoshimori_tannery", "cerrando pieles"),
      r("21:00", "07:00", "loc_hoshimori_tannery", "descansando"),
    ],
  },
  {
    npcId: "npc_nia",
    name: "Nia",
    age: 13,
    role: "recadera ocasional",
    homeLocationId: "loc_hoshimori_plaza",
    currentLocationId: "loc_hoshimori_plaza",
    currentTask: "haciendo recados menores",
    availability: { status: "available", reason: "se mueve rapido entre plaza, mercado y posada" },
    persistenceLevel: "background_prepared",
    personality: ["rapida", "curiosa", "algo imprudente"],
    speechStyle: "rapida y directa",
    values: ["monedas pequenas", "historias nuevas", "ser util"],
    tolerates: ["encargos simples", "preguntas divertidas"],
    rejects: ["adultos que la tratan como tonta", "peligros grandes"],
    routineBase: [
      r("06:00", "12:00", "loc_hoshimori_plaza", "haciendo recados menores"),
      r("12:00", "14:00", "loc_hoshimori_market", "llevando mensajes de mediodia"),
      r("14:00", "18:00", "loc_hoshimori_grulla_azul", "haciendo recados entre posada y mercado"),
      r("18:00", "21:00", "loc_hoshimori_plaza", "volviendo con noticias"),
      r("21:00", "06:00", "loc_hoshimori_plaza", "descansando"),
    ],
  },
  {
    npcId: "npc_doran",
    name: "Doran",
    age: 60,
    role: "ex lenador",
    homeLocationId: "loc_hoshimori_plaza",
    currentLocationId: "loc_hoshimori_plaza",
    currentTask: "observando el movimiento del pueblo",
    availability: { status: "available", reason: "suele estar en plaza o Camino del Molino" },
    persistenceLevel: "background_prepared",
    personality: ["terco", "nostalgico", "observador"],
    speechStyle: "lento, con advertencias viejas",
    values: ["experiencia", "bosque respetado", "jovenes prudentes"],
    tolerates: ["escuchar consejos", "preguntar por rutas"],
    rejects: ["subestimar el bosque", "reirse de viejas heridas"],
    routineBase: [
      r("06:00", "12:00", "loc_hoshimori_plaza", "observando el movimiento del pueblo"),
      r("12:00", "14:00", "loc_hoshimori_plaza", "dando advertencias de mediodia"),
      r("14:00", "18:00", "loc_hoshimori_road_to_mill", "paseando cerca del Camino del Molino"),
      r("18:00", "21:00", "loc_hoshimori_grulla_azul", "buscando cena y charla"),
      r("21:00", "06:00", "loc_hoshimori_plaza", "descansando"),
    ],
  },
  {
    npcId: "npc_maelis",
    name: "Maelis",
    age: 24,
    role: "ayudante del templo",
    homeLocationId: "loc_hoshimori_temple_serene_flame",
    currentLocationId: "loc_hoshimori_temple_serene_flame",
    currentTask: "ayudando en el templo",
    availability: { status: "available", reason: "suele estar en templo o mercado por hierbas" },
    persistenceLevel: "background_prepared",
    personality: ["gentil", "firme", "atenta al dolor ajeno"],
    speechStyle: "suave y clara",
    values: ["cuidado", "calma", "hierbas utiles"],
    tolerates: ["pacientes nerviosos", "preguntas honestas"],
    rejects: ["fingir heridas", "burlarse del duelo"],
    factionLinks: [{ factionId: "faction_hoshimori_temple", role: "ayudante", loyalty: 65 }],
    routineBase: [
      r("06:00", "12:00", "loc_hoshimori_temple_serene_flame", "ayudando en el templo"),
      r("12:00", "14:00", "loc_hoshimori_temple_serene_flame", "atendiendo visitas de mediodia"),
      r("14:00", "17:00", "loc_hoshimori_liora_stall", "buscando hierbas y remedios"),
      r("17:00", "21:00", "loc_hoshimori_temple_serene_flame", "ordenando velas y vendajes"),
      r("21:00", "06:00", "loc_hoshimori_temple_serene_flame", "descansando"),
    ],
  },
  {
    npcId: "npc_joren_pell",
    name: "Joren Pell",
    age: 33,
    role: "comerciante de paso frecuente",
    homeLocationId: "loc_hoshimori_grulla_azul",
    currentLocationId: "loc_hoshimori_grulla_azul",
    currentTask: "descansando o revisando suministros",
    availability: { status: "unknown", reason: "aparece en posada, mercado o rutas segun viaje" },
    persistenceLevel: "background_prepared",
    personality: ["educado", "calculador", "miedoso ante violencia"],
    speechStyle: "cortes, cuidadoso",
    values: ["margen seguro", "rutas abiertas", "no llamar la atencion"],
    tolerates: ["negocios claros", "charla prudente"],
    rejects: ["violencia", "riesgos sin ganancia"],
    routineBase: [
      r("06:00", "10:00", "loc_hoshimori_market", "revisando suministros"),
      r("10:00", "14:00", "loc_hoshimori_grulla_azul", "descansando o revisando suministros"),
      r("14:00", "18:00", "loc_hoshimori_market", "negocios menores en el mercado"),
      r("18:00", "22:00", "loc_hoshimori_grulla_azul", "cenando o escuchando rumores"),
      r("22:00", "06:00", "loc_hoshimori_grulla_azul", "durmiendo como viajero"),
    ],
  },
];

function buildLocationOperation(location) {
  return {
    updateOne: {
      filter: { locationId: location.locationId },
      update: {
        $set: {
          regionId: REGION_ID,
          currentStatus: "operational",
          parentLocationId: "",
          ownerNpcId: "",
          controllingFactionId: "",
          openHours: [],
          activeEffects: [],
          ...location,
        },
      },
      upsert: true,
    },
  };
}

function buildNpcOperation(npc) {
  const payload = {
    ...sharedDefaults,
    ...npc,
    relationshipWithLucas: undefined,
  };

  delete payload.relationshipWithLucas;

  return {
    updateOne: {
      filter: { npcId: npc.npcId },
      update: {
        $set: payload,
        $setOnInsert: {
          relationshipWithLucas: npc.relationshipWithLucas || sharedDefaults.relationshipWithLucas,
        },
      },
      upsert: true,
    },
  };
}

async function seedHoshimoriCore() {
  await connectDB();

  if (mongoose.connection.readyState !== 1) {
    throw new Error("MONGODB_URI is required to seed Hoshimori core data.");
  }

  await Location.bulkWrite(locations.map(buildLocationOperation), { ordered: false });
  await Npc.bulkWrite(npcs.map(buildNpcOperation), { ordered: false });

  const [locationCount, npcCount] = await Promise.all([
    Location.countDocuments({ regionId: REGION_ID }),
    Npc.countDocuments({ regionId: REGION_ID }),
  ]);

  console.log("Hoshimori core seed completed.");
  console.log(`Expected locations in seed: ${locations.length}`);
  console.log(`Expected NPCs in seed: ${npcs.length}`);
  console.log(`MongoDB locations in ${REGION_ID}: ${locationCount}`);
  console.log(`MongoDB NPCs in ${REGION_ID}: ${npcCount}`);

  await mongoose.disconnect();
}

seedHoshimoriCore().catch(async (error) => {
  console.error("Error seeding Hoshimori core:", error.message);
  await mongoose.disconnect();
  process.exit(1);
});
