require("dotenv").config({ quiet: true });

const mongoose = require("mongoose");
const connectDB = require("../config/db");

const Npc = require("../models/Npc");
const NpcMemory = require("../models/NpcMemory");
const NpcRelationship = require("../models/NpcRelationship");

const SOURCE = "c18_hoshimori_npc_living_layer_seed";
const MARKER_TAGS = ["c18", "hoshimori", "npc_living_layer"];
const CREATED_DAY = 18;
const CREATED_TIME = "10:05";

function unique(values = []) {
  return Array.from(new Set(values.filter(Boolean)));
}

function normalizePair(left, right) {
  return [left, right].sort();
}

function profile(npcId, data) {
  return {
    npcId,
    socialProfile: {
      archetype: data.archetype,
      affinityTags: data.affinityTags || [],
      frictionTags: data.frictionTags || [],
      trustSignals: data.trustSignals || [],
      respectSignals: data.respectSignals || [],
      affectionSignals: data.affectionSignals || [],
      suspicionSignals: data.suspicionSignals || [],
      fearSignals: data.fearSignals || [],
      jealousySignals: data.jealousySignals || [],
      boundaries: data.boundaries || [],
      notes: `source:${SOURCE}; ${data.notes || ""}`.trim(),
    },
    livingLayer: {
      schemaVersion: "npc_living_layer_v1",
      currentConcern: data.currentConcern || "",
      personalGoals: data.personalGoals || [],
      agencyHooks: data.agencyHooks || [],
      dialogueExample: data.dialogueExample || "",
      dialogueTexture: data.dialogueTexture || "",
      scenePressure: data.scenePressure || "",
      source: SOURCE,
    },
  };
}

function relationship(left, right, data) {
  const [npcAId, npcBId] = normalizePair(left, right);
  return {
    relationshipId: `rel_${npcAId}_${npcBId}`,
    npcAId,
    npcBId,
    type: data.type,
    trust: data.trust,
    familiarity: data.familiarity,
    tension: data.tension,
    publicSummary: data.publicSummary,
    privateNotes: data.privateNotes || "",
    emotionalTone: data.emotionalTone || "",
    publicTensionReason: data.publicTensionReason || "",
    privateSubtext: data.privateSubtext || "",
    interactionHints: data.interactionHints || [],
    boundaries: data.boundaries || [],
    knownToLucas: data.knownToLucas ?? false,
    source: SOURCE,
    tags: unique([...MARKER_TAGS, SOURCE, ...(data.tags || [])]),
  };
}

function memory(memoryId, npcId, data) {
  return {
    memoryId,
    npcId,
    fact: data.fact,
    summary: data.summary,
    sourceType: data.sourceType || "saw",
    sourceId: SOURCE,
    certainty: data.certainty || "confirmed",
    emotionalWeight: data.emotionalWeight || "low",
    privacyLevel: data.privacyLevel || "semi_private",
    canShare: data.canShare ?? false,
    shareConditions: data.shareConditions || [],
    createdDay: data.createdDay || CREATED_DAY,
    createdTime: data.createdTime || CREATED_TIME,
    lastReferencedDay: data.lastReferencedDay || null,
    importance: data.importance || "normal",
    decayType: data.decayType || "none",
    relatedNpcIds: data.relatedNpcIds || [],
    relatedLocationIds: data.relatedLocationIds || [],
    tags: unique([...MARKER_TAGS, SOURCE, ...(data.tags || [])]),
  };
}

const profiles = [
  profile("npc_roberto_valen", {
    archetype: "pragmatic_employer_with_hidden_care",
    affinityTags: ["reliable_work", "punctuality", "keeps_word", "protects_house"],
    frictionTags: ["excuses", "theft", "broken_shift", "reckless_generosity"],
    trustSignals: ["avisa antes de fallar", "cumple turnos", "admite errores"],
    respectSignals: ["trabajo bien hecho", "cuida la posada", "paga deudas"],
    suspicionSignals: ["excusas flojas", "desorden con cuentas", "promesas vagas"],
    boundaries: ["no pedir adelantos sin causa clara", "no abandonar turno sin avisar", "no usar su confianza como permiso"],
    currentConcern: "Mantener La Grulla Azul estable mientras el barro y los rumores de ruta aprietan suministros.",
    personalGoals: ["que la posada no pierda margen", "proteger a sus trabajadoras sin hacerlo teatro"],
    agencyHooks: ["corta una charla contando monedas", "manda una tarea pequena para medir confiabilidad"],
    dialogueExample: "Si vas a ayudar, ayuda. Si vas a prometer, ponele hora. Lo demas ensucia la mesa.",
    dialogueTexture: "seco, practico, humor gastado que tapa cuidado real",
    scenePressure: "cuentas, turnos, proveedores, comida y reputacion de la casa",
  }),
  profile("npc_fern", {
    archetype: "reserved_boundary_sensitive_helper",
    affinityTags: ["discretion", "quiet_honesty", "safe_magic", "calm_help"],
    frictionTags: ["pressure", "invasion", "reckless_magic", "public_exposure"],
    trustSignals: ["guarda secretos", "pregunta sin invadir", "controla el mana"],
    respectSignals: ["disciplina tranquila", "seguridad", "no usar magia para impresionar"],
    fearSignals: ["magia imprudente", "gritos cerca", "manos invasivas"],
    boundaries: ["no insistir si se cierra", "no invadir espacio personal", "no hablar de magia privada en publico"],
    currentConcern: "Seguir trabajando sin que su cansancio o su talento magico llamen demasiada atencion.",
    personalGoals: ["mantener calma en la posada", "aprender sin quedar expuesta"],
    agencyHooks: ["deja una taza cerca sin anunciarlo", "interrumpe para bajar el tono de una escena"],
    dialogueExample: "No lo digas tan fuerte. Si es importante, podemos hablarlo cuando nadie este mirando.",
    dialogueTexture: "breve, baja, atenta a la salida y a las manos ajenas",
    scenePressure: "privacidad, cansancio, magia segura y cuidado silencioso",
  }),
  profile("npc_yara_mils", {
    archetype: "shy_helper_sensitive_to_public_pressure",
    affinityTags: ["gentle_help", "calm_company", "effort_respected", "patient_correction"],
    frictionTags: ["public_mockery", "rough_flirting", "cruel_comparison", "being_replaced"],
    trustSignals: ["ayuda genuina", "defiende su esfuerzo", "le da espacio para corregirse"],
    respectSignals: ["la trata como trabajadora", "reconoce tareas pequenas", "no la expone"],
    affectionSignals: ["calidez sin presion", "compania tranquila", "gestos cuidadosos"],
    jealousySignals: ["comparaciones crueles", "ignorarla despues de acercarse"],
    boundaries: ["no burlarse en publico", "no forzar coqueteo", "no hablar por ella frente a Roberto"],
    currentConcern: "Ganar un lugar real en La Grulla Azul sin que cada error parezca una sentencia.",
    personalGoals: ["ser util", "aprender el oficio", "no depender de lastima"],
    agencyHooks: ["se adelanta medio paso y luego espera permiso", "corrige una tarea antes de pedir perdon"],
    dialogueExample: "Puedo hacerlo. Solo... decime si esta mal antes de que Roberto lo vea.",
    dialogueTexture: "suave, rapida cuando se pone nerviosa, con orgullo escondido",
    scenePressure: "miradas publicas, trabajo de cocina, inseguridad y ganas de demostrar valor",
  }),
  profile("npc_garrick_thorne", {
    archetype: "guild_mentor_procedural_guardian",
    affinityTags: ["clear_report", "caution", "discipline", "evidence_first"],
    frictionTags: ["reckless_novice", "false_report", "mission_lie", "heroic_noise"],
    trustSignals: ["reporta sin adornar", "pregunta antes de lanzarse", "acepta supervision"],
    respectSignals: ["preparacion", "pruebas", "responsabilidad institucional"],
    suspicionSignals: ["relatos cambiantes", "urgencia sin evidencia", "ocultar riesgo"],
    boundaries: ["no exagerar reportes", "no pedir rango sin cierre formal", "no convertir suerte en merito"],
    currentConcern: "Que el asunto del bosque no crezca por informes incompletos ni novatos ansiosos.",
    personalGoals: ["mantener creible al gremio", "evitar muertes evitables", "coordinar sin humillar"],
    agencyHooks: ["hace una pregunta casual que pesa contradicciones", "traduce la dureza de otro en orden util"],
    dialogueExample: "Si es prueba, la miramos. Si es miedo, tambien. Pero no mezcles una cosa con la otra.",
    dialogueTexture: "claro, serio, protector sin sonar paternal",
    scenePressure: "registro, evidencia, seguridad de novatos y reputacion del gremio",
  }),
  profile("npc_mara_vell", {
    archetype: "procedural_clerk_with_controlled_empathy",
    affinityTags: ["complete_forms", "clear_evidence", "punctuality", "accepts_no"],
    frictionTags: ["touching_files", "pressure_to_skip_rules", "vague_claims", "interrupting_seal"],
    trustSignals: ["datos verificables", "respeto por turnos", "no dramatizar el procedimiento"],
    respectSignals: ["claridad", "pruebas ordenadas", "paciencia administrativa"],
    suspicionSignals: ["versiones cambiantes", "excusas", "apuro interesado"],
    boundaries: ["no tocar archivos", "no exigir promesas que no dio", "no presionarla frente al mostrador"],
    currentConcern: "Cerrar expedientes sin que una palabra mal escrita cree una obligacion falsa.",
    personalGoals: ["proteger al gremio de errores", "separar hecho de ruido", "no ser empujada por ansiedad ajena"],
    agencyHooks: ["corrige una palabra antes de responder", "deja el sello suspendido para enfriar la escena"],
    dialogueExample: "Eso fue una estimacion. Una promesa lleva sello, hora y responsable.",
    dialogueTexture: "formal, seca, exacta; la irritacion baja el volumen",
    scenePressure: "archivos, fechas, pruebas, limites institucionales",
  }),
  profile("npc_eddan_rusk", {
    archetype: "scarred_instructor_practical_care",
    affinityTags: ["real_effort", "retreat_smart", "technical_humility", "admits_limits"],
    frictionTags: ["boasting", "suicidal_novice", "attacks_without_plan", "hunger_as_pride"],
    trustSignals: ["obedece limites", "admite cansancio", "corrige sin teatro"],
    respectSignals: ["retirada inteligente", "postura util", "preguntas tecnicas"],
    fearSignals: ["insiste herido", "busca combate real sin base"],
    boundaries: ["no sparring si el cuerpo miente", "no usar valentia como excusa", "no pedir elogios"],
    currentConcern: "Que Lucas aprenda a sobrevivir antes de pedir combate de verdad.",
    personalGoals: ["cortar malos habitos", "medir novatos sin romperlos", "no repetir entierros viejos"],
    agencyHooks: ["mira los pies antes de la cara", "detiene una practica por un detalle que nadie noto"],
    dialogueExample: "Si tu hombro llega antes que la daga, no atacaste: avisaste donde abrirte.",
    dialogueTexture: "aspero, breve, con imagen concreta del peligro",
    scenePressure: "cuerpo cansado, tecnica, distancia, hambre y orgullo de novato",
  }),
  profile("npc_brann", {
    archetype: "loud_helper_masking_insecurity",
    affinityTags: ["fair_challenge", "public_recognition", "simple_work", "shared_joke"],
    frictionTags: ["public_humiliation", "being_ignored", "treated_as_stupid"],
    trustSignals: ["le dan una tarea clara", "no lo dejan quedar mal", "lo toman en serio"],
    respectSignals: ["fuerza bien usada", "cumplir carga", "competencia sana"],
    suspicionSignals: ["risa cruel", "ordenes como insulto"],
    boundaries: ["no humillarlo frente a otros", "no usarlo solo de chiste"],
    currentConcern: "Encontrar paga y reconocimiento antes de que lo tomen por otro mozo descartable.",
    personalGoals: ["ganar monedas", "lucirse sin fallar", "pegarse a gente competente"],
    agencyHooks: ["sube la voz cuando duda", "se ofrece a cargar algo antes de que se lo pidan"],
    dialogueExample: "Puedo cargar eso. No lo mires tanto, que si lo miro yo tambien pesa mas.",
    dialogueTexture: "bromista, alto, buscando testigos",
    scenePressure: "paga rapida, orgullo, miedo a quedar ultimo",
  }),
  profile("npc_pavo", {
    archetype: "market_vendor_rumor_broker",
    affinityTags: ["good_story", "fair_bargain", "hungry_honesty", "reciprocal_tip"],
    frictionTags: ["aggressive_haggling", "debt_without_guarantee", "wasting_stock"],
    trustSignals: ["paga claro", "comparte rumores utiles", "compra sin teatro"],
    respectSignals: ["regateo divertido", "reconoce margen", "no espanta clientes"],
    suspicionSignals: ["monedas escondidas", "querer fiado", "demasiadas preguntas sin compra"],
    boundaries: ["no pedir fiado sin garantia", "no asustar clientes", "no confundir rumor con promesa"],
    currentConcern: "Convertir barro, hambre y noticias en ventas sin quedar atrapado en deudas.",
    personalGoals: ["mover stock", "saber antes que otros", "mantener clientes sonriendo"],
    agencyHooks: ["baja la voz cuando el rumor vale", "transforma una queja en oferta limitada"],
    dialogueExample: "Te vendo pan seco o informacion fresca. Las dos cosas llenan, pero una sale mas cara.",
    dialogueTexture: "rapido, vendedor, gracioso sin regalar nada",
    scenePressure: "precios, stock, rumores y bolsas de monedas",
  }),
  profile("npc_borin", {
    archetype: "craftsman_guarding_his_work",
    affinityTags: ["tool_respect", "technical_question", "pays_fair", "safe_weapon_use"],
    frictionTags: ["touching_tools", "rushing_work", "wanting_pretty_over_safe", "weapon_on_credit"],
    trustSignals: ["no toca sin permiso", "pregunta por uso real", "cuida el filo"],
    respectSignals: ["pago justo", "respeto por el oficio", "prioriza seguridad"],
    suspicionSignals: ["apuro sin dinero", "culpar herramientas", "querer arma fiada"],
    boundaries: ["no tocar herramientas", "no pedir armas fiadas", "no apurar piezas peligrosas"],
    currentConcern: "Que nadie use una herramienta mal cuidada y despues culpe a su yunque.",
    personalGoals: ["hacer piezas que aguanten", "cobrar lo justo", "mantener idiotas lejos del fuego"],
    agencyHooks: ["responde con el martillo antes que con palabras", "levanta una pieza a la luz para mostrar el defecto"],
    dialogueExample: "Bonito mata a nadie. Seguro, tal vez te deja volver para pagarme.",
    dialogueTexture: "pocas palabras, metal, costo y uso",
    scenePressure: "herramientas, calor, seguridad y orgullo de oficio",
  }),
  profile("npc_sella", {
    archetype: "soft_spoken_social_tailor",
    affinityTags: ["discretion", "careful_detail", "polite_confidence", "paid_privacy"],
    frictionTags: ["gossip_abuse", "last_minute_pressure", "using_trust_as_coin"],
    trustSignals: ["paga discrecion", "nota detalles", "no exige secretos"],
    respectSignals: ["cuidado de presentacion", "paciencia", "trato amable"],
    suspicionSignals: ["preguntas demasiado directas", "usar ropa como excusa para husmear"],
    boundaries: ["no forzar chismes privados", "no exigir arreglos imposibles al instante"],
    currentConcern: "Sostener clientela fiel sin volverse la culpable de cada rumor que cose.",
    personalGoals: ["guardar secretos utiles", "mejorar presentacion de clientes", "cobrar sin perder elegancia"],
    agencyHooks: ["toca una costura mientras piensa", "ofrece arreglar una manga para abrir conversacion"],
    dialogueExample: "Esa manga dice mas que tu cara. Puedo arreglarla; lo otro depende de vos.",
    dialogueTexture: "amable, observadora, filo envuelto en suavidad",
    scenePressure: "ropa, reputacion, secretos y apariencia publica",
  }),
  profile("npc_liora", {
    archetype: "practical_herbalist_market_reader",
    affinityTags: ["direct_customer", "plant_knowledge", "fair_price", "family_recipe"],
    frictionTags: ["theatrical_haggling", "spoiling_stock", "underestimating_kindness"],
    trustSignals: ["compra claro", "escucha advertencias", "no exagera sintomas"],
    respectSignals: ["conoce uso de hierbas", "paga justo", "cuida producto"],
    suspicionSignals: ["pide remedios imposibles", "quiere credito por sonrisa"],
    boundaries: ["no pedir curas milagrosas", "no tocar stock delicado", "no usar amabilidad como descuento"],
    currentConcern: "Que la humedad no arruine hierbas antes de que el mercado las necesite.",
    personalGoals: ["mover producto fresco", "leer clientes rapido", "no quedar atrapada en deudas pequenas"],
    agencyHooks: ["prueba una hoja antes de recomendarla", "lee el hambre antes de que pregunten"],
    dialogueExample: "Eso no cura valentia. Pero ayuda si despues aceptas sentarte.",
    dialogueTexture: "vivaz, practica, sonrisa con defensa",
    scenePressure: "hierbas, salud cotidiana, humedad y pequenos tratos",
  }),
  profile("npc_narek", {
    archetype: "serene_caretaker_with_buried_anger",
    affinityTags: ["honest_pain", "quiet_respect", "helps_temple", "keeps_promise"],
    frictionTags: ["demanding_miracles", "ignoring_rest", "mocking_faith"],
    trustSignals: ["admite dolor", "respeta silencio", "cumple promesas"],
    respectSignals: ["ayuda practica", "escucha consejo", "no confunde fe con atajo"],
    fearSignals: ["desesperacion fanatica", "heridas ocultas"],
    boundaries: ["no exigir curas gratis", "no provocar en el templo", "no ignorar reposo"],
    currentConcern: "Mantener el templo como refugio sin prometer milagros que no existen.",
    personalGoals: ["bajar el ritmo de quien llega roto", "cuidar memoria comunitaria"],
    agencyHooks: ["ofrece agua antes de consejo", "convierte una respuesta en pregunta moral"],
    dialogueExample: "Respira primero. Despues decidimos si eso era coraje o miedo con buen nombre.",
    dialogueTexture: "bajo, pausado, firme debajo de la calma",
    scenePressure: "dolor, promesas, reposo y limites de la ayuda",
  }),
  profile("npc_kael", {
    archetype: "civil_guard_preventing_escalation",
    affinityTags: ["early_warning", "discipline", "calm_public_order", "truth_with_witnesses"],
    frictionTags: ["public_panic", "weapons_in_crowd", "lying_before_witnesses"],
    trustSignals: ["avisa temprano", "mantiene calma", "respeta autoridad civil"],
    respectSignals: ["disciplina", "resolver sin desenvainar", "cuidado con testigos"],
    suspicionSignals: ["arma fuera de lugar", "version confusa", "provocar multitudes"],
    boundaries: ["no blandir armas en zonas civiles", "no crear panico", "no mentir frente a testigos"],
    currentConcern: "Evitar que rumores del bosque o rutas se vuelvan panico en plaza.",
    personalGoals: ["mantener orden sin crueldad", "formar guardias que no abusen"],
    agencyHooks: ["mide salidas antes de hablar", "elige una palabra suave que suena a advertencia"],
    dialogueExample: "Despacio. Si haces que todos miren el arma, ya perdiste la mitad del control.",
    dialogueTexture: "directo, sobrio, advertencia con educacion",
    scenePressure: "multitudes, armas, rumores y autoridad visible",
  }),
  profile("npc_celia_dorn", {
    archetype: "civic_mediator_polished_pressure",
    affinityTags: ["ordered_argument", "consequence_thinking", "protocol_respected"],
    frictionTags: ["public_scandal", "accusation_without_witness", "faction_pressure"],
    trustSignals: ["version breve y clara", "piensa consecuencias", "acepta una salida formal"],
    respectSignals: ["protocolos", "evitar humillacion publica", "mediacion"],
    suspicionSignals: ["buscar ventaja politica", "acusar sin testigo"],
    boundaries: ["no resolver conflictos legales por charla casual", "no usar el consejo como amenaza"],
    currentConcern: "Que un problema chico entre gremio, guardia y mercado no se vuelva crisis publica.",
    personalGoals: ["cerrar discusiones sin destruir caras", "sostener imagen civil"],
    agencyHooks: ["repite una version mejorada de lo que oyo", "ofrece una salida elegante que tambien es limite"],
    dialogueExample: "Dame la version que pueda escribirse sin que manana parezca otra cosa.",
    dialogueTexture: "pulida, administrativa, cansada de incendios pequenos",
    scenePressure: "ley local, imagen publica, mediacion y consecuencias",
  }),
  profile("npc_irma", {
    archetype: "market_memory_keeper",
    affinityTags: ["good_story", "reciprocal_favor", "polite_youth", "small_truth"],
    frictionTags: ["dangerous_lie", "guards_demanding_names", "listening_without_buying"],
    trustSignals: ["comparte detalle util", "no la deja cargar sola con rumor", "trato educado"],
    respectSignals: ["memoria precisa", "favor reciproco", "no confundir charla con tonteria"],
    suspicionSignals: ["quiere nombres", "usa rumor para dano"],
    boundaries: ["no pedir nombres sin causa", "no convertir rumor en certeza", "no culparla por todo lo que oye"],
    currentConcern: "Saber que se mueve por el mercado sin ser culpada si una mentira lastima.",
    personalGoals: ["mantener red de favores", "recordar quien dijo que y cuando"],
    agencyHooks: ["rie antes de preguntar lo importante", "corrige un detalle menor para mostrar que sabe mas"],
    dialogueExample: "Eso no fue lo que oiste. Fue lo que te dejaron oir, que es distinto.",
    dialogueTexture: "risuena, inquisitiva, memoria con sonrisa",
    scenePressure: "rumores, favores, nombres y dano social",
  }),
  profile("npc_sael_nyra", {
    archetype: "restless_adventurer_chasing_openings",
    affinityTags: ["clean_mystery", "chosen_risk", "useful_companion", "no_trapping_questions"],
    frictionTags: ["closed_promise", "being_treated_as_useless", "long_wait", "owing_too_much"],
    trustSignals: ["respeta su salida", "comparte oportunidad", "no exige deuda"],
    respectSignals: ["competencia visible", "riesgo elegido", "pista limpia"],
    suspicionSignals: ["preguntas insistentes", "promesas cerradas", "querer atarla"],
    boundaries: ["no confundir curiosidad con disponibilidad", "no pedir promesa cerrada sin pago", "no tratarla como adorno"],
    currentConcern: "Encontrar una oportunidad real antes de que el gremio local se vuelva jaula.",
    personalGoals: ["saber antes que los demas", "subir sin deber demasiado", "elegir sus riesgos"],
    agencyHooks: ["gira una moneda mientras mide la salida", "deja caer una pista y mira quien la recoge"],
    dialogueExample: "Si eso muerde, paga. Si solo asusta, todavia puede servirnos.",
    dialogueTexture: "viva, rapida, medio desafio, media verdad",
    scenePressure: "oportunidades, deuda, libertad y misterio",
  }),
  profile("npc_oren", {
    archetype: "mill_worker_grounded_by_routes",
    affinityTags: ["helps_load", "clear_payment", "route_warning", "practical_silence"],
    frictionTags: ["badly_tied_load", "dragged_into_fight", "promise_speed"],
    trustSignals: ["ayuda con peso real", "paga claro", "advierte peligros de camino"],
    respectSignals: ["cuida animales y cargas", "mira huellas antes de opinar"],
    suspicionSignals: ["promete rapidez imposible", "toca carga ajena"],
    boundaries: ["no tocar carga sin permiso", "no meterlo en pleitos", "no apurar animales cansados"],
    currentConcern: "Mantener molino y cargas funcionando aunque rutas y barro cambien el dia.",
    personalGoals: ["llegar con todo entero", "evitar pleitos ajenos", "no vararse con mercancia"],
    agencyHooks: ["revisa nudos mientras escucha", "discute una ruta mirando barro"],
    dialogueExample: "El camino no se convence con prisa. O aguanta el peso, o te lo cobra.",
    dialogueTexture: "prudente, cordial, manos ocupadas",
    scenePressure: "cargas, rutas, barro y pago claro",
  }),
  profile("npc_tessa", {
    archetype: "fast_local_carrier_hiding_fatigue",
    affinityTags: ["route_tip", "efficient_help", "paid_on_time", "respects_schedule"],
    frictionTags: ["late_cargo", "making_her_wait", "danger_without_warning"],
    trustSignals: ["avisa demoras", "paga a tiempo", "no la manda a ciegas"],
    respectSignals: ["eficiencia", "conoce rutas", "cuida transporte"],
    suspicionSignals: ["carga sospechosa", "ocultar peligro"],
    boundaries: ["no hacerla esperar sin pago", "no ocultar riesgo de ruta", "no tratar transporte como favor gratis"],
    currentConcern: "Que las rutas sigan pagando aunque todos quieran rapidez sin costo.",
    personalGoals: ["cerrar entregas", "evitar quedar atrapada en barro", "saber que camino esta vivo"],
    agencyHooks: ["mira el cielo a mitad de frase", "calcula distancia con los dedos"],
    dialogueExample: "Puedo llevarlo. No puedo hacer que el barro tenga modales.",
    dialogueTexture: "rapida, luminosa, cansancio bien doblado",
    scenePressure: "rutas, horarios, clima y clientes impacientes",
  }),
  profile("npc_doran", {
    archetype: "old_woodcutter_with_forest_memory",
    affinityTags: ["respects_forest", "listens_to_old_warnings", "quiet_courage"],
    frictionTags: ["mocking_old_fears", "charging_blindly", "loud_heroics"],
    trustSignals: ["escucha antes de entrar al bosque", "no se burla de advertencias"],
    respectSignals: ["prudencia", "conoce marcas", "no presume"],
    suspicionSignals: ["quiere historia para hacerse grande", "ignora senales viejas"],
    fearSignals: ["ruido en bosque", "rastro sin nombre"],
    boundaries: ["no burlarse de memorias del bosque", "no pedir certeza donde solo hay senales"],
    currentConcern: "Que los jovenes vuelvan a tratar al bosque como cuento hasta que deje de serlo.",
    personalGoals: ["no volver a cargar a nadie desde los arboles", "que sus advertencias sirvan una vez"],
    agencyHooks: ["mira la linea de arboles antes de contestar", "corta una historia justo antes del detalle peor"],
    dialogueExample: "Las marcas raras no piden permiso. Primero las ves; despues decidis si queres dormir.",
    dialogueTexture: "ronco, lento, memoria que pesa",
    scenePressure: "bosque, edad, advertencias y miedo no resuelto",
  }),
  profile("npc_hilda_fen", {
    archetype: "warm_baker_with_hard_limits",
    affinityTags: ["pays_for_food", "helps_children", "honest_hunger", "community_care"],
    frictionTags: ["wasting_food", "abusive_debt", "mocking_poverty"],
    trustSignals: ["paga cuando puede", "no miente sobre hambre", "ayuda sin mirar publico"],
    respectSignals: ["no desperdicia", "cuida familias", "trata deudas con dignidad"],
    affectionSignals: ["gentle_kindness", "remembers_small_needs"],
    suspicionSignals: ["querer pan fiado como costumbre", "usar lastima"],
    boundaries: ["no desperdiciar comida", "no abusar de deudas", "no humillar pobres"],
    currentConcern: "Que el pan alcance para vender y para no dejar a ciertas familias sin nada.",
    personalGoals: ["alimentar sin quebrar", "mantener clientes dignos", "medir heridas escondidas"],
    agencyHooks: ["chasquea la lengua antes de ordenar", "interrumpe para mirar el color de alguien"],
    dialogueExample: "Come despacio. El orgullo no mastica por vos.",
    dialogueTexture: "calida hasta que se cruza un limite",
    scenePressure: "pan, hambre, deudas y cuidado comunitario",
  }),
  profile("npc_merek_sol", {
    archetype: "tanner_who_reads_damage_in_materials",
    affinityTags: ["practical_trade", "clean_hides", "respects_dirty_work", "honest_origin"],
    frictionTags: ["lying_about_source", "mocking_smell", "unsafe_beast_parts"],
    trustSignals: ["dice de donde viene el material", "no desprecia el oficio", "paga por trabajo sucio"],
    respectSignals: ["calidad de pieles", "cuidado sanitario", "trato practico"],
    suspicionSignals: ["piel rara sin historia", "ocultar mordidas o enfermedad"],
    boundaries: ["no traer restos peligrosos sin avisar", "no burlarse del olor", "no mentir origen"],
    currentConcern: "Que una piel rara o enferma meta problemas en el pueblo antes de que alguien pregunte.",
    personalGoals: ["trabajar sin enfermar a otros", "cobrar lo que nadie quiere tocar"],
    agencyHooks: ["huele antes de mirar", "se lava las manos aunque no haya terminado"],
    dialogueExample: "Si eso vino del bosque, no lo pongas en mi mesa como si fuera cuero normal.",
    dialogueTexture: "seco, nasal, oficio sucio con orgullo",
    scenePressure: "pieles, enfermedad, origen de materiales y rechazo social",
  }),
  profile("npc_rulan_veck", {
    archetype: "guard_apprentice_eager_to_prove",
    affinityTags: ["clear_order", "training_respect", "public_calm", "admits_mistake"],
    frictionTags: ["being_mocked", "undermined_in_public", "panic"],
    trustSignals: ["corrige sin humillar", "da orden clara", "reconoce aprendizaje"],
    respectSignals: ["disciplina", "control de multitud", "aceptar error"],
    suspicionSignals: ["lo usan para saltarse autoridad", "lo provocan frente a Kael"],
    jealousySignals: ["compararlo con guardias mejores"],
    boundaries: ["no humillarlo frente a Kael", "no usarlo para esquivar reglas"],
    currentConcern: "Demostrar que puede ser guardia sin parecer un chico con cinturon prestado.",
    personalGoals: ["ganar respeto de Kael", "no congelarse en publico"],
    agencyHooks: ["endereza postura tarde", "repite una orden como si probara el peso"],
    dialogueExample: "La orden es esperar. Y... esta vez la dije antes de que Kael me mire.",
    dialogueTexture: "formal de mas, energia joven contenida",
    scenePressure: "aprendizaje, autoridad, verguenza publica",
  }),
  profile("npc_maelis", {
    archetype: "temple_helper_gentle_but_not_naive",
    affinityTags: ["quiet_help", "honest_need", "respect_for_care", "small_service"],
    frictionTags: ["using_kindness", "demanding_free_work", "mocking_prayer"],
    trustSignals: ["pide ayuda sin actuar derecho absoluto", "agradece tareas pequenas"],
    respectSignals: ["cuida enfermos", "respeta el templo", "no presiona a Narek"],
    suspicionSignals: ["busca cura sin escuchar", "usa pena para manipular"],
    boundaries: ["no usar ternura como moneda", "no exigirle decidir por Narek"],
    currentConcern: "Aprender a ayudar sin dejar que todos confundan gentileza con disponibilidad infinita.",
    personalGoals: ["ser util en el templo", "sostener calma sin borrarse"],
    agencyHooks: ["acomoda una vela torcida", "ofrece agua y despues pregunta lo dificil"],
    dialogueExample: "Puedo ayudarte a sentarte. Lo demas hay que pedirlo bien.",
    dialogueTexture: "suave, clara, firme cuando toca limite",
    scenePressure: "cuidado, fe cotidiana, limites de servicio",
  }),
  profile("npc_nia", {
    archetype: "quick_errand_runner_collecting_fragments",
    affinityTags: ["small_tip", "clear_message", "safe_errand", "kind_attention"],
    frictionTags: ["dangerous_errand", "being_ignored", "false_message"],
    trustSignals: ["mensaje claro", "pago pequeno justo", "no la manda a peligro"],
    respectSignals: ["rapidez", "memoria de detalles", "cumple recados"],
    suspicionSignals: ["encargo secreto raro", "adultos que mienten con sonrisa"],
    fearSignals: ["rutas peligrosas", "gritos de adultos"],
    boundaries: ["no mandarla a peligro", "no usarla para mensajes crueles", "no tratarla como invisible"],
    currentConcern: "Juntar monedas y noticias sin terminar en medio de problemas de adultos.",
    personalGoals: ["hacer recados rapidos", "ser tomada en serio", "no quedar atrapada en discusiones"],
    agencyHooks: ["aparece con una noticia incompleta", "mira si hay propina antes de terminar la frase"],
    dialogueExample: "Yo puedo llevarlo, pero si gritan despues, no fui yo la que lo dijo.",
    dialogueTexture: "rapida, curiosa, medio pie fuera de la escena",
    scenePressure: "mensajes, monedas pequenas, peligro de adultos",
  }),
  profile("npc_joren_pell", {
    archetype: "polite_traveling_merchant_weighing_risk",
    affinityTags: ["reliable_route_info", "careful_trade", "polite_bargain", "shared_supply_news"],
    frictionTags: ["violence_near_goods", "unclear_debt", "being_trapped"],
    trustSignals: ["informa rutas", "no exagera riesgo", "paga lo acordado"],
    respectSignals: ["calculo cuidadoso", "trato educado", "sabe retirarse"],
    suspicionSignals: ["demasiada prisa", "carga sin origen", "deuda confusa"],
    fearSignals: ["violencia en posada", "ruta sin testigos"],
    boundaries: ["no arrastrarlo a pelea", "no pedir credito ambiguo", "no tocar suministros sin permiso"],
    currentConcern: "Saber si Hoshimori sigue siendo parada rentable o un riesgo con camas.",
    personalGoals: ["mover suministros", "evitar violencia", "vender informacion sin quedar pegado"],
    agencyHooks: ["sonrie mientras calcula salida", "pregunta por clima antes de preguntar por precio"],
    dialogueExample: "La ruta puede esperar. Mi mercancia no puede sangrar por una decision ajena.",
    dialogueTexture: "cortes, cuidadoso, miedo convertido en modales",
    scenePressure: "suministros, rutas, violencia y calculo comercial",
  }),
];

const relationships = [
  relationship("npc_mara_vell", "npc_eddan_rusk", {
    type: "guild_procedure_vs_training",
    trust: 54,
    familiarity: 68,
    tension: 24,
    publicSummary: "Mara y Eddan coordinan evaluaciones y registros del gremio, aunque discuten metodo y ritmo.",
    emotionalTone: "respeto con friccion entre papel y cuerpo",
    publicTensionReason: "Mara exige cierre defendible; Eddan quiere limites fisicos antes que formularios.",
    privateSubtext: "Ambos protegen novatos, pero desconfian del lenguaje del otro.",
    interactionHints: ["Mara traduce una orden brusca en registro", "Eddan corta una demora si ve riesgo fisico"],
    boundaries: ["no hacerlos enemigos caricaturescos"],
    tags: ["guild", "procedure", "training"],
  }),
  relationship("npc_garrick_thorne", "npc_sael_nyra", {
    type: "guild_opportunity_tension",
    trust: 31,
    familiarity: 44,
    tension: 28,
    publicSummary: "Garrick conoce a Sael como aventurera novata que busca oportunidades, util si no exagera.",
    emotionalTone: "vigilancia cordial",
    publicTensionReason: "Sael quiere moverse rapido; Garrick quiere reportes claros.",
    privateSubtext: "Garrick ve potencial y riesgo; Sael teme quedar atrapada en permisos.",
    interactionHints: ["Garrick le pide precision cuando Sael vende una pista", "Sael convierte advertencias en desafio"],
    boundaries: ["Sael no debe recibir encargos formales sin validacion"],
    tags: ["guild", "adventurer", "opportunity"],
  }),
  relationship("npc_mara_vell", "npc_sael_nyra", {
    type: "guild_clerk_adventurer_friction",
    trust: 24,
    familiarity: 38,
    tension: 34,
    publicSummary: "Mara y Sael se cruzan por registros, permisos y encargos menores del gremio.",
    emotionalTone: "paciencia administrativa contra energia inquieta",
    publicTensionReason: "Sael quiere respuestas rapidas; Mara exige papeles limpios.",
    privateSubtext: "Mara no odia la ambicion de Sael, pero no le regalara margen.",
    interactionHints: ["Mara corrige una palabra que Sael intenta estirar", "Sael bromea justo antes de obedecer"],
    boundaries: ["no convertir friccion en hostilidad fuerte sin escena"],
    tags: ["guild", "paperwork"],
  }),
  relationship("npc_eddan_rusk", "npc_sael_nyra", {
    type: "trainer_reckless_novice",
    trust: 26,
    familiarity: 42,
    tension: 36,
    publicSummary: "Eddan ha visto a Sael entrenar y no confia en su impulso, aunque reconoce que aprende rapido.",
    emotionalTone: "choque entre prisa y supervivencia",
    publicTensionReason: "Sael busca oportunidad; Eddan ve errores que matan.",
    privateSubtext: "Eddan la corrige mas duro porque no quiere verla quebrarse.",
    interactionHints: ["Eddan corta su entusiasmo con imagen concreta", "Sael intenta sonreir como si no doliera"],
    boundaries: ["Eddan no humilla por crueldad"],
    tags: ["guild", "training", "reckless"],
  }),
  relationship("npc_roberto_valen", "npc_pavo", {
    type: "inn_market_supply_trade",
    trust: 44,
    familiarity: 64,
    tension: 18,
    publicSummary: "Roberto y Pavo negocian alimentos, raciones y noticias del mercado para La Grulla Azul.",
    emotionalTone: "trato comercial con bromas cansadas",
    publicTensionReason: "Pavo vende margen; Roberto compra estabilidad.",
    privateSubtext: "Ambos saben que se necesitan mas de lo que admiten.",
    interactionHints: ["Pavo convierte escasez en historia", "Roberto corta la historia con una cifra"],
    boundaries: ["no regalar suministros sin economia"],
    tags: ["market", "inn", "supplies"],
  }),
  relationship("npc_roberto_valen", "npc_hilda_fen", {
    type: "inn_bakery_supply",
    trust: 50,
    familiarity: 62,
    tension: 14,
    publicSummary: "Roberto compra pan y noticias practicas a Hilda cuando la posada necesita sostener comidas.",
    emotionalTone: "respeto seco entre gente que alimenta a otros",
    publicTensionReason: "Ambos entienden hambre y cuentas, pero ninguno puede regalar demasiado.",
    privateSubtext: "Comparten una compasion que disfrazan de precio correcto.",
    interactionHints: ["Hilda nota si Roberto compra menos pan", "Roberto paga sin pedir lastima"],
    boundaries: ["no convertir ayuda comunitaria en dinero gratis"],
    tags: ["inn", "bakery", "food"],
  }),
  relationship("npc_roberto_valen", "npc_joren_pell", {
    type: "inn_traveling_merchant",
    trust: 36,
    familiarity: 54,
    tension: 16,
    publicSummary: "Joren usa La Grulla Azul como parada frecuente y Roberto lo mide como cliente y fuente de ruta.",
    emotionalTone: "cortesia con calculo mutuo",
    publicTensionReason: "Joren quiere seguridad; Roberto quiere pago y datos confiables.",
    privateSubtext: "Ambos prefieren parecer menos preocupados por rutas de lo que estan.",
    interactionHints: ["Joren pregunta por camas antes de hablar de miedo", "Roberto oye la ruta escondida en el pedido"],
    boundaries: ["no resolver suministros por charla casual"],
    tags: ["inn", "travel", "merchant"],
  }),
  relationship("npc_hilda_fen", "npc_pavo", {
    type: "market_food_neighbors",
    trust: 38,
    familiarity: 70,
    tension: 20,
    publicSummary: "Hilda y Pavo comparten clientes de comida en el mercado y compiten sin romper trato.",
    emotionalTone: "vecindad ruidosa con limites",
    publicTensionReason: "Pavo exagera; Hilda no tolera desperdicio ni deuda abusiva.",
    privateSubtext: "Hilda sabe cuando Pavo esta realmente preocupado por stock.",
    interactionHints: ["Hilda corta una exageracion con una mirada", "Pavo le baja la voz si el rumor toca hambre"],
    boundaries: ["no volverlos caricatura de mercado"],
    tags: ["market", "food"],
  }),
  relationship("npc_hilda_fen", "npc_irma", {
    type: "market_memory_and_care",
    trust: 45,
    familiarity: 76,
    tension: 18,
    publicSummary: "Hilda e Irma se conocen del mercado y cruzan noticias sobre familias, deudas y hambre.",
    emotionalTone: "charla calida con responsabilidad",
    publicTensionReason: "Irma quiere saber; Hilda teme que una palabra lastime a alguien pobre.",
    privateSubtext: "Se cubren cuando el rumor puede convertirse en dano.",
    interactionHints: ["Irma baja la voz al pasar por la panadera", "Hilda cambia pan por silencio util"],
    boundaries: ["rumores de pobreza no deben sonar comicos"],
    tags: ["market", "rumors", "care"],
  }),
  relationship("npc_narek", "npc_hilda_fen", {
    type: "temple_bakery_care",
    trust: 48,
    familiarity: 58,
    tension: 8,
    publicSummary: "Narek e Hilda coordinan ayuda discreta cuando alguien necesita comida o descanso.",
    emotionalTone: "cuidado comunitario sin ceremonia",
    publicTensionReason: "Hilda piensa en pan; Narek piensa en reposo y dignidad.",
    privateSubtext: "Ambos ayudan mas de lo que podrian admitir en cuentas.",
    interactionHints: ["Narek pregunta por alguien sin decir nombre", "Hilda responde con una bolsa ya preparada"],
    boundaries: ["no usar caridad como solucion infinita"],
    tags: ["temple", "bakery", "care"],
  }),
  relationship("npc_borin", "npc_kael", {
    type: "smith_guard_equipment",
    trust: 46,
    familiarity: 58,
    tension: 12,
    publicSummary: "Borin mantiene equipo que Kael necesita para guardias, patrullas y reparaciones menores.",
    emotionalTone: "respeto practico entre oficio y orden",
    publicTensionReason: "Kael quiere disponibilidad; Borin no apura metal inseguro.",
    privateSubtext: "Kael confia en Borin porque prefiere un no a una pieza mala.",
    interactionHints: ["Borin muestra defecto sin explicar demasiado", "Kael acepta esperar si entiende el riesgo"],
    boundaries: ["no crear armas gratis ni instantaneas"],
    tags: ["smithy", "guard", "equipment"],
  }),
  relationship("npc_borin", "npc_merek_sol", {
    type: "dirty_trades_material_exchange",
    trust: 32,
    familiarity: 48,
    tension: 18,
    publicSummary: "Borin y Merek se cruzan por correas, cuero, reparaciones y materiales que otros no quieren tocar.",
    emotionalTone: "oficios duros con poca paciencia social",
    publicTensionReason: "Ambos odian apuros y clientes que desprecian trabajo sucio.",
    privateSubtext: "Se respetan porque ninguno finge que el trabajo sea bonito.",
    interactionHints: ["Merek avisa si una piel no sirve", "Borin grune menos si el material llega honesto"],
    boundaries: ["materiales raros requieren origen claro"],
    tags: ["craft", "materials"],
  }),
  relationship("npc_kael", "npc_doran", {
    type: "guard_old_warning",
    trust: 30,
    familiarity: 42,
    tension: 22,
    publicSummary: "Kael escucha a Doran cuando el viejo habla de bosque, aunque no siempre puede actuar con rumores.",
    emotionalTone: "prudencia tensa",
    publicTensionReason: "Doran habla desde memoria; Kael necesita algo defendible ante testigos.",
    privateSubtext: "Kael teme ignorar una advertencia vieja justo la vez que importa.",
    interactionHints: ["Doran da una frase incompleta", "Kael pregunta por testigos antes de descartar"],
    boundaries: ["no convertir advertencias en certeza sin evidencia"],
    tags: ["guard", "forest", "warning"],
  }),
  relationship("npc_kael", "npc_tessa", {
    type: "guard_route_coordination",
    trust: 42,
    familiarity: 50,
    tension: 12,
    publicSummary: "Kael y Tessa cruzan avisos de ruta, entradas al pueblo y problemas de transporte.",
    emotionalTone: "coordinacion breve de gente ocupada",
    publicTensionReason: "Tessa necesita moverse; Kael necesita que el peligro se diga antes.",
    privateSubtext: "Ambos valoran la rapidez, pero solo si vuelve alguien vivo.",
    interactionHints: ["Tessa da un dato de camino como queja", "Kael lo convierte en advertencia publica"],
    boundaries: ["rutas peligrosas no deben trivializarse"],
    tags: ["guard", "routes"],
  }),
  relationship("npc_oren", "npc_tessa", {
    type: "mill_transport_route_work",
    trust: 40,
    familiarity: 56,
    tension: 10,
    publicSummary: "Oren y Tessa coordinan cargas, molino y caminos cuando el barro cambia horarios.",
    emotionalTone: "trabajo sin adorno",
    publicTensionReason: "Oren piensa en peso; Tessa piensa en tiempo.",
    privateSubtext: "Se entienden mejor cuando ambos siguen moviendo las manos.",
    interactionHints: ["Oren mira nudos mientras Tessa calcula minutos", "Tessa acepta una demora si Oren senala el peso"],
    boundaries: ["no convertir transporte en teletransporte narrativo"],
    tags: ["mill", "routes", "transport"],
  }),
  relationship("npc_oren", "npc_joren_pell", {
    type: "mill_merchant_supply",
    trust: 34,
    familiarity: 46,
    tension: 16,
    publicSummary: "Oren y Joren tratan por molienda, cargas y suministros que pasan por Hoshimori.",
    emotionalTone: "cortesia practica con calculo",
    publicTensionReason: "Joren busca margen; Oren no promete camino facil.",
    privateSubtext: "Ambos saben que una ruta mala arruina mas que una venta.",
    interactionHints: ["Joren pregunta como si fuera casual", "Oren responde mirando el barro"],
    boundaries: ["no crear suministro sin stock/ruta"],
    tags: ["mill", "merchant", "supply"],
  }),
  relationship("npc_tessa", "npc_joren_pell", {
    type: "carrier_merchant_route_bargain",
    trust: 30,
    familiarity: 52,
    tension: 24,
    publicSummary: "Tessa y Joren negocian rutas, tiempos y riesgo cuando hay mercancia de paso.",
    emotionalTone: "negociacion viva",
    publicTensionReason: "Joren quiere seguridad barata; Tessa quiere que el riesgo se pague.",
    privateSubtext: "Tessa nota cuando el miedo de Joren dice mas que sus modales.",
    interactionHints: ["Tessa corta una rebaja con dato de camino", "Joren sonrie cuando quiere retroceder"],
    boundaries: ["el riesgo de ruta debe tener costo"],
    tags: ["routes", "merchant", "transport"],
  }),
  relationship("npc_nia", "npc_yara_mils", {
    type: "errand_runner_inn_helper",
    trust: 28,
    familiarity: 46,
    tension: 8,
    publicSummary: "Nia y Yara se cruzan por recados de posada, cocina y mensajes pequenos.",
    emotionalTone: "juventud trabajadora con nervios distintos",
    publicTensionReason: "Nia corre; Yara intenta no equivocarse.",
    privateSubtext: "Yara ve en Nia una version mas libre y mas expuesta de si misma.",
    interactionHints: ["Nia entra con media noticia", "Yara intenta ordenarla antes de que Roberto la oiga"],
    boundaries: ["no mandar a Nia a peligro"],
    tags: ["inn", "errands", "youth"],
  }),
  relationship("npc_nia", "npc_irma", {
    type: "errands_and_rumor_lessons",
    trust: 24,
    familiarity: 44,
    tension: 12,
    publicSummary: "Irma usa a veces a Nia para recados pequenos y le ensena, sin admitirlo, a escuchar el mercado.",
    emotionalTone: "curiosidad guiada con riesgo",
    publicTensionReason: "Irma quiere datos; Nia puede quedar en medio.",
    privateSubtext: "Irma protege a Nia mas de lo que parece cuando pregunta.",
    interactionHints: ["Irma pregunta como si fuera compra", "Nia repite solo la mitad segura"],
    boundaries: ["no usar menores para secretos peligrosos"],
    tags: ["market", "errands", "rumors"],
  }),
  relationship("npc_nia", "npc_maelis", {
    type: "errand_temple_kindness",
    trust: 35,
    familiarity: 40,
    tension: 4,
    publicSummary: "Nia lleva recados menores al templo y Maelis suele corregirla con suavidad.",
    emotionalTone: "cuidado ligero",
    publicTensionReason: "Nia quiere rapidez; Maelis quiere que no se lastime.",
    privateSubtext: "Maelis reconoce en Nia una necesidad de ser vista.",
    interactionHints: ["Maelis ofrece agua antes de preguntar", "Nia finge que no la necesitaba"],
    boundaries: ["mantener tono inocente y no romantizar menores"],
    tags: ["temple", "errands", "care"],
  }),
  relationship("npc_celia_dorn", "npc_narek", {
    type: "civic_temple_coordination",
    trust: 52,
    familiarity: 58,
    tension: 10,
    publicSummary: "Celia y Narek coordinan ayuda comunitaria, duelos, promesas y problemas que no conviene hacer escandalo.",
    emotionalTone: "formalidad con compasion contenida",
    publicTensionReason: "Celia necesita forma; Narek necesita calma humana.",
    privateSubtext: "Ambos entienden que una decision publica puede curar o humillar.",
    interactionHints: ["Celia ofrece palabras defendibles", "Narek baja el ritmo de la decision"],
    boundaries: ["no resolver asuntos civicos por fe improvisada"],
    tags: ["council", "temple", "community"],
  }),
  relationship("npc_celia_dorn", "npc_mara_vell", {
    type: "records_cross_institution",
    trust: 48,
    familiarity: 54,
    tension: 18,
    publicSummary: "Celia y Mara se cruzan por registros del consejo y el gremio cuando un expediente toca ambas instituciones.",
    emotionalTone: "precision formal con competencia tranquila",
    publicTensionReason: "Ambas quieren palabras exactas, pero responden a autoridades distintas.",
    privateSubtext: "Se respetan porque ninguna regala una firma.",
    interactionHints: ["Mara corrige el dato minimo", "Celia reformula para que no escale"],
    boundaries: ["no saltar proceso legal por simpatia"],
    tags: ["records", "guild", "council"],
  }),
  relationship("npc_sael_nyra", "npc_joren_pell", {
    type: "adventurer_merchant_information_trade",
    trust: 20,
    familiarity: 28,
    tension: 22,
    publicSummary: "Sael y Joren se miden cuando una ruta o rumor puede convertirse en oportunidad pagada.",
    emotionalTone: "curiosidad con calculo y miedo",
    publicTensionReason: "Sael quiere moverse hacia el riesgo; Joren quiere venderlo desde lejos.",
    privateSubtext: "Cada uno piensa que el otro subestima el costo real.",
    interactionHints: ["Sael pide el detalle que Joren omite", "Joren sonrie cuando quiere no ir"],
    boundaries: ["no convertir rumores en mision sin backend"],
    tags: ["adventurer", "merchant", "rumor"],
  }),
];

const memories = [
  memory("memory_c18_borin_tools_not_toys", "npc_borin", {
    fact: "Borin recuerda que novatos y guardias rompen equipo cuando tratan herramientas como juguetes.",
    summary: "Borin mide a cualquier recien llegado por como mira o toca herramientas antes de hablar de armas.",
    relatedLocationIds: ["loc_hoshimori_borin_smithy"],
    tags: ["craft", "tools", "boundaries"],
  }),
  memory("memory_c18_brann_yara_work_pressure", "npc_brann", {
    fact: "Brann ha visto a Yara cargarse de trabajo en La Grulla Azul para no parecer reemplazable.",
    summary: "Brann bromea con Yara, pero sabe que ella se pone nerviosa cuando la miran trabajar.",
    sourceType: "saw",
    certainty: "probable",
    relatedNpcIds: ["npc_yara_mils"],
    relatedLocationIds: ["loc_hoshimori_grulla_azul"],
    tags: ["inn", "yara", "work_pressure"],
  }),
  memory("memory_c18_celia_guild_records_delays", "npc_celia_dorn", {
    fact: "Celia sabe que los registros entre consejo, guardia y gremio pueden trabarse si una frase queda ambigua.",
    summary: "Celia trata los retrasos administrativos como riesgo civico pequeno, no como simple molestia.",
    sourceType: "public_record",
    relatedNpcIds: ["npc_mara_vell", "npc_garrick_thorne"],
    relatedLocationIds: ["loc_hoshimori_council_records", "loc_hoshimori_guild"],
    tags: ["records", "council", "guild"],
  }),
  memory("memory_c18_doran_old_forest_warnings", "npc_doran", {
    fact: "Doran recuerda advertencias viejas del bosque que empezaron como rastros faciles de ignorar.",
    summary: "Doran no afirma saber que ocurre ahora, pero desconfia de marcas raras cerca del bosque.",
    sourceType: "heard",
    certainty: "probable",
    emotionalWeight: "medium",
    relatedLocationIds: ["loc_hoshimori_forest_edge"],
    tags: ["forest", "warning", "rumor_boundary"],
  }),
  memory("memory_c18_hilda_food_debt_map", "npc_hilda_fen", {
    fact: "Hilda lleva en la cabeza que familias compran menos pan cuando las rutas se atrasan.",
    summary: "Hilda nota hambre y deuda antes que la mayoria, pero no lo convierte en espectaculo.",
    sourceType: "saw",
    relatedLocationIds: ["loc_hoshimori_market"],
    tags: ["market", "food", "debt", "care"],
  }),
  memory("memory_c18_irma_market_names", "npc_irma", {
    fact: "Irma recuerda quien dijo cada rumor y delante de quien, aunque rara vez lo suelta completo.",
    summary: "Irma trata el mercado como una red de favores, no solo como chisme.",
    sourceType: "heard",
    relatedLocationIds: ["loc_hoshimori_market"],
    tags: ["market", "rumors", "memory"],
  }),
  memory("memory_c18_joren_muddy_supply_delays", "npc_joren_pell", {
    fact: "Joren ha visto que el barro y los retrasos de ruta cambian precios y humor en la posada.",
    summary: "Joren pregunta por caminos con modales de comerciante, pero calcula riesgo antes que cortesia.",
    sourceType: "saw",
    relatedNpcIds: ["npc_roberto_valen", "npc_tessa"],
    relatedLocationIds: ["loc_hoshimori_grulla_azul", "loc_hoshimori_road_entrance"],
    tags: ["routes", "supplies", "merchant"],
  }),
  memory("memory_c18_kael_mill_road_chatter", "npc_kael", {
    fact: "Kael ha oido conversaciones nerviosas sobre huellas y rutas cercanas al molino.",
    summary: "Kael no trata rumores como evidencia, pero los usa para decidir donde mirar primero.",
    sourceType: "heard",
    certainty: "rumor",
    relatedLocationIds: ["loc_hoshimori_mill_road", "loc_hoshimori_plaza"],
    tags: ["guard", "route", "rumor_boundary"],
  }),
  memory("memory_c18_liora_damp_stock", "npc_liora", {
    fact: "Liora sabe que la humedad cambia que hierbas sobreviven al mercado y que remedios pide la gente.",
    summary: "Liora lee clima, hambre y verguenza como parte del trato, no como charla decorativa.",
    sourceType: "saw",
    relatedLocationIds: ["loc_hoshimori_liora_stall", "loc_hoshimori_market"],
    tags: ["herbs", "weather", "market"],
  }),
  memory("memory_c18_maelis_narek_rest_first", "npc_maelis", {
    fact: "Maelis ha visto a Narek mandar a la gente a respirar y sentarse antes de hablar de soluciones.",
    summary: "Maelis aprendio que ayudar tambien incluye decir no con suavidad.",
    sourceType: "saw",
    relatedNpcIds: ["npc_narek"],
    relatedLocationIds: ["loc_hoshimori_temple_serene_flame"],
    tags: ["temple", "care", "boundaries"],
  }),
  memory("memory_c18_merek_odd_hides", "npc_merek_sol", {
    fact: "Merek se preocupa cuando una piel llega con marcas raras y nadie puede explicar su origen.",
    summary: "Merek no quiere material del bosque en su mesa sin historia clara.",
    sourceType: "saw",
    certainty: "probable",
    relatedLocationIds: ["loc_hoshimori_tannery", "loc_hoshimori_forest_edge"],
    tags: ["materials", "forest", "origin"],
  }),
  memory("memory_c18_narek_forest_lights_caution", "npc_narek", {
    fact: "Narek ha escuchado rumores de luces y sensaciones raras cerca del bosque.",
    summary: "Narek los trata como preocupacion comunitaria, no como certeza religiosa ni magica.",
    sourceType: "heard",
    certainty: "rumor",
    relatedLocationIds: ["loc_hoshimori_temple_serene_flame", "loc_hoshimori_forest_edge"],
    tags: ["temple", "forest", "rumor_boundary"],
  }),
  memory("memory_c18_nia_adults_half_messages", "npc_nia", {
    fact: "Nia sabe que los adultos a veces le dan medio mensaje y esperan que no pregunte el resto.",
    summary: "Nia recuerda detalles pequenos de recados, pero evita quedar atrapada cuando empiezan los gritos.",
    sourceType: "saw",
    emotionalWeight: "low",
    relatedLocationIds: ["loc_hoshimori_plaza"],
    tags: ["errands", "youth", "messages"],
  }),
  memory("memory_c18_oren_mill_road_weight", "npc_oren", {
    fact: "Oren sabe que una ruta cambia segun peso, barro y hora, no segun ganas.",
    summary: "Oren mira barro y nudos antes de prometer tiempos.",
    sourceType: "saw",
    relatedLocationIds: ["loc_hoshimori_mill", "loc_hoshimori_mill_road"],
    tags: ["mill", "routes", "weight"],
  }),
  memory("memory_c18_pavo_prices_follow_mud", "npc_pavo", {
    fact: "Pavo sabe que el barro y los rumores de ruta mueven precios incluso antes de que falte stock.",
    summary: "Pavo usa noticias como parte del precio, pero distingue rumor vendible de certeza.",
    sourceType: "heard",
    relatedNpcIds: ["npc_tessa", "npc_joren_pell"],
    relatedLocationIds: ["loc_hoshimori_market"],
    tags: ["market", "prices", "routes"],
  }),
  memory("memory_c18_rulan_kael_crowd_lesson", "npc_rulan_veck", {
    fact: "Rulan recuerda que Kael lo corrigio por hablar tarde cuando una pequena multitud ya estaba mirando.",
    summary: "Rulan intenta parecer firme antes de sentirse listo.",
    sourceType: "saw",
    relatedNpcIds: ["npc_kael"],
    relatedLocationIds: ["loc_hoshimori_guard_post", "loc_hoshimori_plaza"],
    tags: ["guard", "training", "public_pressure"],
  }),
  memory("memory_c18_sael_lucas_guild_forest_chatter", "npc_sael_nyra", {
    fact: "Sael ha visto a Lucas moverse por el gremio mientras el asunto del bosque sigue flotando en conversaciones.",
    summary: "Sael cree que puede haber oportunidad alrededor de Lucas y el bosque, pero no conoce los detalles privados.",
    sourceType: "saw",
    certainty: "probable",
    emotionalWeight: "medium",
    relatedNpcIds: ["npc_garrick_thorne", "npc_mara_vell"],
    relatedLocationIds: ["loc_hoshimori_guild"],
    tags: ["guild", "lucas", "forest", "opportunity", "knowledge_boundary"],
  }),
  memory("memory_c18_sella_clothes_show_mood", "npc_sella", {
    fact: "Sella nota cambios de animo por como la gente lleva ropa, barro, mangas y botones.",
    summary: "Sella usa detalles de presentacion para abrir conversaciones sin parecer invasiva.",
    sourceType: "saw",
    relatedLocationIds: ["loc_hoshimori_sella_workshop", "loc_hoshimori_market"],
    tags: ["tailor", "social_reading", "discretion"],
  }),
  memory("memory_c18_tessa_route_delays_cost", "npc_tessa", {
    fact: "Tessa sabe que cada demora de ruta tiene costo aunque el cliente quiera llamarlo favor.",
    summary: "Tessa advierte peligros de camino si le dicen la verdad antes de cargar.",
    sourceType: "saw",
    relatedLocationIds: ["loc_hoshimori_road_entrance"],
    tags: ["routes", "transport", "cost"],
  }),
];

async function assertReferences() {
  const npcIds = unique([
    ...profiles.map((entry) => entry.npcId),
    ...relationships.flatMap((entry) => [entry.npcAId, entry.npcBId]),
    ...memories.map((entry) => entry.npcId),
    ...memories.flatMap((entry) => entry.relatedNpcIds || []),
  ]);
  const existing = await Npc.find({ npcId: { $in: npcIds } }).distinct("npcId");
  const missing = npcIds.filter((npcId) => !existing.includes(npcId));

  if (missing.length) {
    throw new Error(`Missing NPCs for living layer seed: ${missing.join(", ")}`);
  }
}

async function seedHoshimoriNpcLivingLayer() {
  await connectDB();

  if (mongoose.connection.readyState !== 1) {
    throw new Error("MONGODB_URI is required to seed Hoshimori NPC living layer.");
  }

  await assertReferences();

  await Npc.bulkWrite(
    profiles.map((entry) => ({
      updateOne: {
        filter: { npcId: entry.npcId },
        update: {
          $set: {
            socialProfile: entry.socialProfile,
            "flags.livingLayer": entry.livingLayer,
            "flags.livingLayerSource": SOURCE,
          },
        },
      },
    })),
    { ordered: false }
  );

  await NpcRelationship.bulkWrite(
    relationships.map((entry) => ({
      updateOne: {
        filter: { npcAId: entry.npcAId, npcBId: entry.npcBId },
        update: { $set: entry },
        upsert: true,
      },
    })),
    { ordered: false }
  );

  await NpcMemory.bulkWrite(
    memories.map((entry) => ({
      updateOne: {
        filter: { memoryId: entry.memoryId },
        update: { $set: entry },
        upsert: true,
      },
    })),
    { ordered: false }
  );

  const [profileCount, relationshipCount, memoryCount] = await Promise.all([
    Npc.countDocuments({ "flags.livingLayerSource": SOURCE }),
    NpcRelationship.countDocuments({ source: SOURCE }),
    NpcMemory.countDocuments({ sourceId: SOURCE }),
  ]);

  console.log("Hoshimori NPC living layer seed completed.");
  console.log(`NPC profiles updated: ${profileCount}`);
  console.log(`NPC relationships with source ${SOURCE}: ${relationshipCount}`);
  console.log(`NPC memories with source ${SOURCE}: ${memoryCount}`);

  await mongoose.disconnect();
}

if (require.main === module) {
  seedHoshimoriNpcLivingLayer().catch(async (error) => {
    console.error("Error seeding Hoshimori NPC living layer:", error.message);
    await mongoose.disconnect();
    process.exit(1);
  });
}

module.exports = {
  SOURCE,
  profiles,
  relationships,
  memories,
  seedHoshimoriNpcLivingLayer,
};
