require("dotenv").config({ quiet: true });

const mongoose = require("mongoose");
const connectDB = require("../config/db");

const MagicDiscipline = require("../models/MagicDiscipline");
const MagicTechnique = require("../models/MagicTechnique");

const SOURCE = "g11_magic_basics_seed";
const MARKER_TAGS = ["g11", "magic", "basics"];

function tags(extra = []) {
  return Array.from(new Set([...MARKER_TAGS, SOURCE, ...extra]));
}

function skill(skillId, minLevel = 1, minPhase = "Principiante") {
  return { skillId, minPhase, minLevel };
}

function discipline(disciplineId, data) {
  return {
    disciplineId,
    name: data.name,
    parentDisciplineId: data.parentDisciplineId || "",
    type: data.type || "branch",
    description: data.description || "",
    unlockRequirements: data.unlockRequirements || { skills: [], notes: "" },
    socialRisk: data.socialRisk || "low",
    order: data.order || 0,
    source: SOURCE,
    tags: tags(data.tags || []),
  };
}

function technique(techniqueId, data) {
  return {
    techniqueId,
    name: data.name,
    disciplineId: data.disciplineId,
    kind: data.kind,
    status: data.status || "available",
    description: data.description || "",
    defaultMinutes: data.defaultMinutes || 30,
    minMinutes: data.minMinutes || 5,
    maxMinutes: data.maxMinutes || 120,
    activityCategory: data.activityCategory || "descanso_sentado",
    difficulty: data.difficulty || "basic",
    mpCost: data.mpCost || { fixed: 0, min: 0, max: 0, notes: "" },
    requirements: data.requirements || { skills: [], knownTechniqueIds: [], notes: "" },
    expSuggestions: data.expSuggestions || [],
    isRealSpell: Boolean(data.isRealSpell),
    isAdvanced: Boolean(data.isAdvanced),
    isOffensive: Boolean(data.isOffensive),
    canUnlockAutomatically: Boolean(data.canUnlockAutomatically),
    publicUseRisk: data.publicUseRisk || "low",
    effectProfile: data.effectProfile || {
      effectType: data.isRealSpell ? (data.isOffensive ? "offense" : "utility") : "none",
      damageType: "",
      targetType: "none",
      rangeBand: "none",
      combatUse: data.isOffensive ? "offensive_simple" : data.isRealSpell ? "unsupported" : "practice_only",
      mechanicalNotes: [],
      narrationLimits: [],
    },
    safetyNotes: data.safetyNotes || [],
    source: SOURCE,
    tags: tags(data.tags || []),
  };
}

const disciplines = [
  discipline("discipline_mana", {
    name: "Mana",
    type: "foundation",
    description: "Sensibilidad, reserva y circulacion interna de mana.",
    socialRisk: "low",
    order: 1,
    tags: ["foundation"],
  }),
  discipline("discipline_magic", {
    name: "Magia",
    type: "foundation",
    description: "Estructura, teoria y conversion controlada de mana en efecto.",
    unlockRequirements: { skills: [skill("skill_mana", 1)], notes: "Requiere mana despertado." },
    socialRisk: "medium",
    order: 2,
    tags: ["foundation"],
  }),
  discipline("discipline_magic_perception", {
    name: "Percepcion magica",
    type: "sense",
    description: "Lectura basica de sensaciones y flujo magico sin interpretacion avanzada.",
    unlockRequirements: { skills: [skill("skill_mana", 1), skill("skill_magia", 1)], notes: "" },
    socialRisk: "low",
    order: 3,
    tags: ["sense"],
  }),
  discipline("discipline_offensive_magic", {
    name: "Magia ofensiva",
    parentDisciplineId: "discipline_magic",
    type: "branch",
    description: "Rama de efectos de dano o presion; no es segura para practica publica.",
    unlockRequirements: { skills: [skill("skill_magia", 2), skill("skill_mana", 2)], notes: "" },
    socialRisk: "high",
    order: 4,
    tags: ["offense", "restricted"],
  }),
  discipline("discipline_fire", {
    name: "Fuego",
    parentDisciplineId: "discipline_offensive_magic",
    type: "element",
    description: "Elemento ofensivo de calor y llama; bloqueado para Lucas sin instructor.",
    unlockRequirements: { skills: [skill("skill_magia_ofensiva", 2), skill("skill_mana", 3)], notes: "" },
    socialRisk: "high",
    order: 5,
    tags: ["element", "locked"],
  }),
  discipline("discipline_lightning", {
    name: "Rayo/Electricidad",
    parentDisciplineId: "discipline_offensive_magic",
    type: "element",
    description: "Elemento de descarga y conduccion; requiere control ofensivo previo.",
    unlockRequirements: { skills: [skill("skill_magia_ofensiva", 3), skill("skill_mana", 3)], notes: "" },
    socialRisk: "high",
    order: 6,
    tags: ["element", "locked"],
  }),
  discipline("discipline_ice", {
    name: "Hielo",
    parentDisciplineId: "discipline_offensive_magic",
    type: "element",
    description: "Elemento de frio y cristalizacion simple; no disponible para Lucas todavia.",
    unlockRequirements: { skills: [skill("skill_magia_ofensiva", 2), skill("skill_mana", 3)], notes: "" },
    socialRisk: "high",
    order: 7,
    tags: ["element", "locked"],
  }),
  discipline("discipline_earth_wind", {
    name: "Tierra/Viento",
    parentDisciplineId: "discipline_offensive_magic",
    type: "element",
    description: "Rama elemental mixta de fuerza fisica y movimiento de aire/tierra.",
    unlockRequirements: {
      skills: [skill("skill_magia_ofensiva", 4), skill("skill_magia", 4), skill("skill_mana", 4)],
      notes: "",
    },
    socialRisk: "high",
    order: 8,
    tags: ["element", "locked"],
  }),
  discipline("discipline_defensive_magic", {
    name: "Magia defensiva",
    parentDisciplineId: "discipline_magic",
    type: "branch",
    description: "Rama de proteccion, resistencia y mitigacion.",
    unlockRequirements: { skills: [skill("skill_magia", 3), skill("skill_mana", 3)], notes: "" },
    socialRisk: "medium",
    order: 9,
    tags: ["defense", "locked"],
  }),
  discipline("discipline_magic_resistance", {
    name: "Resistencia magica",
    parentDisciplineId: "discipline_defensive_magic",
    type: "branch",
    description: "Rama de acondicionamiento y respuesta contra presion magica hostil; no anula hechizos gratis.",
    unlockRequirements: { skills: [skill("skill_magia_defensiva", 2), skill("skill_mana", 3)], notes: "" },
    socialRisk: "medium",
    order: 10,
    tags: ["defense", "resistance", "locked"],
  }),
  discipline("discipline_healing_magic", {
    name: "Magia curativa",
    parentDisciplineId: "discipline_magic",
    type: "branch",
    description: "Rama regulada y rara; no equivale a curacion milagrosa gratuita.",
    unlockRequirements: { skills: [skill("skill_magia", 5), skill("skill_mana", 5)], notes: "" },
    socialRisk: "high",
    order: 11,
    tags: ["healing", "locked"],
  }),
  discipline("discipline_mental_magic", {
    name: "Magia mental",
    parentDisciplineId: "discipline_magic",
    type: "specialized",
    description: "Rama socialmente sensible; requiere gran control y percepcion.",
    unlockRequirements: {
      skills: [skill("skill_magia", 5, "Novato"), skill("skill_mana", 5, "Novato"), skill("skill_percepcion", 8)],
      notes: "",
    },
    socialRisk: "high",
    order: 12,
    tags: ["mental", "locked"],
  }),
  discipline("discipline_summoning_magic", {
    name: "Magia de invocacion",
    parentDisciplineId: "discipline_magic",
    type: "specialized",
    description: "Rama avanzada de pactos o llamados; fuera del alcance actual.",
    unlockRequirements: {
      skills: [
        skill("skill_magia", 3, "Competente"),
        skill("skill_mana", 3, "Competente"),
        skill("skill_percepcion_magica", 8, "Novato"),
      ],
      notes: "",
    },
    socialRisk: "high",
    order: 13,
    tags: ["summoning", "locked"],
  }),
];

const techniques = [
  technique("technique_mana_breathing_basic", {
    name: "Respiracion de mana basica",
    disciplineId: "discipline_mana",
    kind: "practice",
    description: "Ejercicio tranquilo para ordenar respiracion y atencion interna. No produce efecto visible.",
    defaultMinutes: 30,
    minMinutes: 10,
    maxMinutes: 60,
    activityCategory: "descanso_sentado",
    difficulty: "safe",
    mpCost: { fixed: 0, min: 0, max: 0, notes: "Sin coste MP si se hace con calma." },
    requirements: { skills: [skill("skill_mana", 1)], knownTechniqueIds: [], notes: "Mana despertado." },
    expSuggestions: [
      {
        skillId: "skill_mana",
        skillName: "Mana",
        category: "practica_basica_10_30min",
        baseExp: 4,
        reason: "Practica basica de mana de 30 minutos.",
      },
    ],
    publicUseRisk: "none",
    safetyNotes: ["No desbloquea hechizos.", "No genera efectos visibles si se practica en reposo."],
    tags: ["initial", "safe", "no_spell_unlock"],
  }),
  technique("technique_internal_flow_sense", {
    name: "Sentir flujo interno",
    disciplineId: "discipline_mana",
    kind: "exercise",
    description: "Ejercicio para notar sensaciones internas de mana sin forzar salida ni efecto externo.",
    defaultMinutes: 20,
    minMinutes: 10,
    maxMinutes: 45,
    activityCategory: "descanso_sentado",
    difficulty: "safe",
    mpCost: { fixed: 0, min: 0, max: 0, notes: "" },
    requirements: { skills: [skill("skill_mana", 1)], knownTechniqueIds: [], notes: "" },
    expSuggestions: [
      {
        skillId: "skill_mana",
        skillName: "Mana",
        category: "practica_basica_10_30min",
        baseExp: 3,
        reason: "Sentir mana interno sin canalizar.",
      },
    ],
    publicUseRisk: "none",
    safetyNotes: ["No empujar mana fuera del cuerpo.", "Detener si causa mareo."],
    tags: ["initial", "safe", "internal"],
  }),
  technique("technique_mana_meditation_basic", {
    name: "Meditacion de mana",
    disciplineId: "discipline_mana",
    kind: "practice",
    description: "Meditacion profunda para estabilizar la atencion sobre la reserva de mana.",
    defaultMinutes: 60,
    minMinutes: 30,
    maxMinutes: 90,
    activityCategory: "descanso_acostado",
    difficulty: "safe",
    mpCost: { fixed: 0, min: 0, max: 0, notes: "" },
    requirements: { skills: [skill("skill_mana", 1)], knownTechniqueIds: [], notes: "" },
    expSuggestions: [
      {
        skillId: "skill_mana",
        skillName: "Mana",
        category: "meditacion_profunda_1h",
        baseExp: 6,
        reason: "Meditacion de mana de una hora.",
      },
    ],
    publicUseRisk: "none",
    safetyNotes: ["No reemplaza descanso completo.", "No desbloquea hechizos por si misma."],
    tags: ["initial", "safe", "meditation"],
  }),
  technique("technique_magic_perception_basic", {
    name: "Percepcion magica basica",
    disciplineId: "discipline_magic_perception",
    kind: "exercise",
    description: "Observar sensaciones de flujo sin interpretar hilos avanzados ni rastros complejos.",
    defaultMinutes: 30,
    minMinutes: 10,
    maxMinutes: 45,
    activityCategory: "descanso_sentado",
    difficulty: "basic",
    mpCost: { fixed: 5, min: 5, max: 5, notes: "Coste orientativo de percepcion magica basica." },
    requirements: { skills: [skill("skill_mana", 1), skill("skill_magia", 1)], knownTechniqueIds: [], notes: "" },
    expSuggestions: [
      {
        skillId: "skill_percepcion_magica",
        skillName: "Percepcion magica",
        category: "practica_percepcion_magica_30min",
        baseExp: 8,
        reason: "Percepcion magica basica de 30 minutos.",
        allowVirtualSkillPreview: true,
      },
    ],
    publicUseRisk: "low",
    safetyNotes: ["No permite ver hilos avanzados.", "No identifica hechizos complejos."],
    tags: ["initial", "safe", "perception"],
  }),
  technique("technique_magic_structure_theory_beginner", {
    name: "Teoria de estructura magica principiante",
    disciplineId: "discipline_magic",
    kind: "theory",
    description: "Estudio conceptual sobre forma, intencion y limite. No crea efectos por si solo.",
    defaultMinutes: 30,
    minMinutes: 15,
    maxMinutes: 90,
    activityCategory: "descanso_sentado",
    difficulty: "safe",
    mpCost: { fixed: 0, min: 0, max: 0, notes: "" },
    requirements: { skills: [skill("skill_magia", 1), skill("skill_mana", 1)], knownTechniqueIds: [], notes: "" },
    expSuggestions: [
      {
        skillId: "skill_magia",
        skillName: "Magia",
        category: "leer_teoria_30min",
        baseExp: 2,
        reason: "Teoria principiante durante 30 minutos.",
      },
    ],
    publicUseRisk: "none",
    safetyNotes: ["Teoria no equivale a hechizo.", "Requiere practica guiada para efectos reales."],
    tags: ["initial", "safe", "theory"],
  }),
  technique("technique_safe_rest_channeling", {
    name: "Canalizacion segura en reposo",
    disciplineId: "discipline_mana",
    kind: "practice",
    description: "Mover atencion y mana de forma contenida en reposo, sin proyeccion externa.",
    defaultMinutes: 30,
    minMinutes: 15,
    maxMinutes: 45,
    activityCategory: "descanso_sentado",
    difficulty: "basic",
    mpCost: { fixed: 0, min: 0, max: 0, notes: "Sin coste si no se fuerza salida externa." },
    requirements: { skills: [skill("skill_mana", 1), skill("skill_magia", 1)], knownTechniqueIds: [], notes: "" },
    expSuggestions: [
      {
        skillId: "skill_mana",
        skillName: "Mana",
        category: "practica_basica_10_30min",
        baseExp: 4,
        reason: "Canalizacion contenida y segura.",
      },
    ],
    publicUseRisk: "low",
    safetyNotes: ["No proyectar mana al ambiente.", "No crea luz, fuego, curacion ni defensa real."],
    tags: ["initial", "safe", "channeling"],
  }),
  technique("technique_offensive_magic_safety_theory", {
    name: "Teoria segura de magia ofensiva",
    disciplineId: "discipline_offensive_magic",
    kind: "theory",
    description: "Estudio de vector, limite, distancia y peligro antes de intentar cualquier efecto ofensivo real.",
    defaultMinutes: 60,
    minMinutes: 30,
    maxMinutes: 90,
    activityCategory: "descanso_sentado",
    difficulty: "basic",
    mpCost: { fixed: 0, min: 0, max: 0, notes: "" },
    requirements: { skills: [skill("skill_magia_ofensiva", 1), skill("skill_mana", 2)], knownTechniqueIds: [], notes: "Requiere rama ofensiva desbloqueada." },
    expSuggestions: [
      {
        skillId: "skill_magia_ofensiva",
        skillName: "Magia ofensiva",
        category: "teoria_ofensiva_1h",
        baseExp: 2,
        reason: "Teoria segura de magia ofensiva durante una hora.",
      },
    ],
    publicUseRisk: "low",
    safetyNotes: ["No produce efecto externo.", "No permite lanzar ataques sin una tecnica/hechizo formal."],
    tags: ["catalog", "theory", "offense", "no_spell_unlock"],
  }),
  technique("technique_defensive_magic_safety_theory", {
    name: "Teoria segura de magia defensiva",
    disciplineId: "discipline_defensive_magic",
    kind: "theory",
    description: "Estudio de pantalla, cobertura, angulo y fallo seguro sin formar barreras reales.",
    defaultMinutes: 60,
    minMinutes: 30,
    maxMinutes: 90,
    activityCategory: "descanso_sentado",
    difficulty: "basic",
    mpCost: { fixed: 0, min: 0, max: 0, notes: "" },
    requirements: { skills: [skill("skill_magia_defensiva", 1), skill("skill_mana", 3)], knownTechniqueIds: [], notes: "Requiere rama defensiva desbloqueada." },
    expSuggestions: [
      {
        skillId: "skill_magia_defensiva",
        skillName: "Magia defensiva",
        category: "teoria_defensiva_1h",
        baseExp: 2,
        reason: "Teoria segura de magia defensiva durante una hora.",
      },
    ],
    publicUseRisk: "low",
    safetyNotes: ["No crea escudo real.", "No bloquea dano sin hechizo conocido y backend especifico."],
    tags: ["catalog", "theory", "defense", "no_spell_unlock"],
  }),
  technique("technique_healing_magic_ethics_theory", {
    name: "Teoria etica de magia curativa",
    disciplineId: "discipline_healing_magic",
    kind: "theory",
    description: "Estudio de limite, estabilizacion y riesgo medico; no cura heridas por si mismo.",
    defaultMinutes: 60,
    minMinutes: 30,
    maxMinutes: 90,
    activityCategory: "descanso_sentado",
    difficulty: "intermediate",
    mpCost: { fixed: 0, min: 0, max: 0, notes: "" },
    requirements: { skills: [skill("skill_magia_curativa", 1), skill("skill_magia", 5), skill("skill_mana", 5)], knownTechniqueIds: [], notes: "Rama rara y regulada." },
    expSuggestions: [
      {
        skillId: "skill_magia_curativa",
        skillName: "Magia curativa",
        category: "teoria_curativa_1h",
        baseExp: 2,
        reason: "Teoria curativa prudente durante una hora.",
      },
    ],
    publicUseRisk: "medium",
    safetyNotes: ["No restaura vida.", "No reemplaza vendajes, reposo ni tratamiento real."],
    tags: ["catalog", "theory", "healing", "regulated", "no_spell_unlock"],
  }),
  technique("technique_mental_magic_ethics_theory", {
    name: "Teoria etica de magia mental",
    disciplineId: "discipline_mental_magic",
    kind: "theory",
    description: "Estudio de limites, consentimiento y riesgo social. No lee pensamientos ni controla voluntades.",
    defaultMinutes: 60,
    minMinutes: 30,
    maxMinutes: 90,
    activityCategory: "descanso_sentado",
    difficulty: "advanced",
    mpCost: { fixed: 0, min: 0, max: 0, notes: "" },
    requirements: {
      skills: [skill("skill_magia_mental", 1), skill("skill_magia", 5, "Novato"), skill("skill_mana", 5, "Novato"), skill("skill_percepcion", 8)],
      knownTechniqueIds: [],
      notes: "Rama socialmente sensible.",
    },
    expSuggestions: [
      {
        skillId: "skill_magia_mental",
        skillName: "Magia mental",
        category: "teoria_mental_1h",
        baseExp: 1,
        reason: "Teoria mental prudente durante una hora.",
      },
    ],
    publicUseRisk: "high",
    safetyNotes: ["No leer pensamientos secretos.", "No manipular emociones o decisiones por narracion."],
    tags: ["catalog", "theory", "mental", "restricted", "no_spell_unlock"],
  }),
  technique("technique_summoning_anchor_theory", {
    name: "Teoria de anclaje de invocacion",
    disciplineId: "discipline_summoning_magic",
    kind: "theory",
    description: "Estudio avanzado de ancla, pacto, llamado y cierre. No invoca criaturas ni entidades.",
    defaultMinutes: 60,
    minMinutes: 30,
    maxMinutes: 120,
    activityCategory: "descanso_sentado",
    difficulty: "advanced",
    mpCost: { fixed: 0, min: 0, max: 0, notes: "" },
    requirements: {
      skills: [skill("skill_magia_invocacion", 1), skill("skill_magia", 3, "Competente"), skill("skill_mana", 3, "Competente"), skill("skill_percepcion_magica", 8, "Novato")],
      knownTechniqueIds: [],
      notes: "Rama fuera del alcance temprano de Lucas.",
    },
    expSuggestions: [
      {
        skillId: "skill_magia_invocacion",
        skillName: "Magia de invocacion",
        category: "teoria_invocacion_1h",
        baseExp: 1,
        reason: "Teoria de invocacion durante una hora.",
      },
    ],
    publicUseRisk: "high",
    safetyNotes: ["No invoca nada.", "No crea pactos sin origen, costo y backend."],
    tags: ["catalog", "theory", "summoning", "restricted", "no_spell_unlock"],
  }),
  technique("technique_magic_resistance_conditioning", {
    name: "Acondicionamiento de resistencia magica",
    disciplineId: "discipline_magic_resistance",
    kind: "exercise",
    description: "Ejercicio contenido para reconocer presion magica y sostener el pulso interno sin anular hechizos.",
    defaultMinutes: 30,
    minMinutes: 15,
    maxMinutes: 60,
    activityCategory: "descanso_sentado",
    difficulty: "intermediate",
    mpCost: { fixed: 5, min: 5, max: 5, notes: "Coste bajo por tension defensiva interna." },
    requirements: { skills: [skill("skill_resistencia_magica", 1), skill("skill_mana", 3)], knownTechniqueIds: [], notes: "Requiere rama de resistencia magica desbloqueada." },
    expSuggestions: [
      {
        skillId: "skill_resistencia_magica",
        skillName: "Resistencia magica",
        category: "exposicion_controlada_30min",
        baseExp: 2,
        reason: "Acondicionamiento interno de resistencia magica.",
      },
    ],
    publicUseRisk: "medium",
    effectProfile: {
      effectType: "resistance",
      damageType: "",
      targetType: "self",
      rangeBand: "none",
      combatUse: "practice_only",
      mechanicalNotes: ["No reduce dano sin un resolver especifico.", "Sirve como practica de condicionamiento."],
      narrationLimits: ["Narrar tension interna, no inmunidad.", "No anular efectos magicos por narracion."],
    },
    safetyNotes: ["Detener si causa mareo.", "No convierte a Lucas en inmune a magia."],
    tags: ["catalog", "exercise", "resistance", "no_spell_unlock"],
  }),
  technique("technique_locked_offensive_spark", {
    name: "Chispa ofensiva controlada",
    disciplineId: "discipline_fire",
    kind: "spell",
    status: "locked_template",
    description: "Plantilla bloqueada de efecto ofensivo minimo. No esta aprendida por Lucas.",
    defaultMinutes: 10,
    minMinutes: 10,
    maxMinutes: 10,
    activityCategory: "actividad_normal",
    difficulty: "advanced",
    mpCost: { fixed: 15, min: 15, max: 15, notes: "No debe gastarse en preview bloqueada." },
    requirements: {
      skills: [skill("skill_magia_ofensiva", 3), skill("skill_mana", 3)],
      knownTechniqueIds: [],
      notes: "Requiere rama ofensiva y control de mana mayor al actual.",
    },
    expSuggestions: [
      {
        skillId: "skill_magia_ofensiva",
        skillName: "Magia ofensiva",
        category: "uso_hechizo_ofensivo_conocido",
        baseExp: 3,
        reason: "Uso o practica de chispa ofensiva ya conocida.",
        allowVirtualSkillPreview: true,
      },
    ],
    isRealSpell: true,
    isAdvanced: true,
    isOffensive: true,
    canUnlockAutomatically: false,
    publicUseRisk: "high",
    effectProfile: {
      effectType: "offense",
      damageType: "burn",
      targetType: "single_enemy",
      rangeBand: "short",
      combatUse: "offensive_simple",
      mechanicalNotes: ["Hechizo ofensivo minimo para resolver por backend.", "El dano, fallo y coste MP los calcula combate avanzado."],
      narrationLimits: ["No narrar incendio grande.", "No narrar dano si el backend no resolvio impacto."],
    },
    safetyNotes: ["Bloqueado para Lucas.", "No practicar en publico.", "No desbloquear automaticamente."],
    tags: ["locked", "spell_template", "offensive", "not_learned"],
  }),
  technique("technique_locked_fire_ember_bolt", {
    name: "Brasa dirigida menor",
    disciplineId: "discipline_fire",
    kind: "spell",
    status: "locked_template",
    description: "Plantilla bloqueada de proyectil igneo pequeno y controlado. Requiere rama de Fuego formal.",
    defaultMinutes: 10,
    minMinutes: 10,
    maxMinutes: 10,
    activityCategory: "actividad_normal",
    difficulty: "advanced",
    mpCost: { fixed: 20, min: 20, max: 20, notes: "Coste de hechizo elemental principiante debil." },
    requirements: {
      skills: [skill("skill_fuego", 1), skill("skill_magia_ofensiva", 3), skill("skill_mana", 3)],
      knownTechniqueIds: [],
      notes: "Requiere desbloquear Fuego; no basta con teoria general.",
    },
    expSuggestions: [
      {
        skillId: "skill_fuego",
        skillName: "Fuego",
        category: "uso_hechizo_elemental_conocido",
        baseExp: 3,
        reason: "Uso de hechizo de fuego conocido.",
      },
    ],
    isRealSpell: true,
    isAdvanced: true,
    isOffensive: true,
    canUnlockAutomatically: false,
    publicUseRisk: "high",
    effectProfile: {
      effectType: "offense",
      damageType: "burn",
      targetType: "single_enemy",
      rangeBand: "short",
      combatUse: "offensive_simple",
      mechanicalNotes: ["Plantilla de dano igneo menor.", "No crea fuego persistente salvo resolucion explicita futura."],
      narrationLimits: ["No incendiar entorno sin resolver riesgo.", "No usar como antorcha gratis."],
    },
    safetyNotes: ["No practicar en publico.", "Riesgo de quemadura o alarma social.", "No desbloquear automaticamente."],
    tags: ["catalog", "locked", "spell_template", "offensive", "fire", "not_learned"],
  }),
  technique("technique_locked_lightning_static_discharge", {
    name: "Descarga estatica dirigida",
    disciplineId: "discipline_lightning",
    kind: "spell",
    status: "locked_template",
    description: "Plantilla bloqueada de descarga electrica breve. Requiere rama de Rayo/Electricidad formal.",
    defaultMinutes: 10,
    minMinutes: 10,
    maxMinutes: 10,
    activityCategory: "actividad_normal",
    difficulty: "advanced",
    mpCost: { fixed: 25, min: 25, max: 25, notes: "Coste de hechizo elemental principiante debil." },
    requirements: {
      skills: [skill("skill_rayo", 1), skill("skill_magia_ofensiva", 3), skill("skill_mana", 3)],
      knownTechniqueIds: [],
      notes: "Rayo/Electricidad requiere control ofensivo y mana estable.",
    },
    expSuggestions: [
      {
        skillId: "skill_rayo",
        skillName: "Rayo/Electricidad",
        category: "uso_hechizo_elemental_conocido",
        baseExp: 3,
        reason: "Uso de descarga electrica conocida.",
      },
    ],
    isRealSpell: true,
    isAdvanced: true,
    isOffensive: true,
    canUnlockAutomatically: false,
    publicUseRisk: "high",
    effectProfile: {
      effectType: "offense",
      damageType: "shock",
      targetType: "single_enemy",
      rangeBand: "short",
      combatUse: "offensive_simple",
      mechanicalNotes: ["Plantilla de dano electrico menor.", "Conduccion, agua y metal requieren resolucion futura especifica."],
      narrationLimits: ["No paralizar gratis.", "No afectar multiples objetivos sin backend."],
    },
    safetyNotes: ["No practicar cerca de agua, metal o publico.", "No desbloquear automaticamente."],
    tags: ["catalog", "locked", "spell_template", "offensive", "lightning", "not_learned"],
  }),
  technique("technique_locked_ice_shard", {
    name: "Esquirla de hielo inicial",
    disciplineId: "discipline_ice",
    kind: "spell",
    status: "locked_template",
    description: "Plantilla bloqueada de fragmento frio pequeno. Requiere rama de Hielo formal.",
    defaultMinutes: 10,
    minMinutes: 10,
    maxMinutes: 10,
    activityCategory: "actividad_normal",
    difficulty: "advanced",
    mpCost: { fixed: 25, min: 25, max: 25, notes: "Coste de hechizo elemental principiante debil." },
    requirements: {
      skills: [skill("skill_hielo", 1), skill("skill_magia_ofensiva", 2), skill("skill_mana", 3)],
      knownTechniqueIds: [],
      notes: "Hielo requiere rama elemental y mana estable.",
    },
    expSuggestions: [
      {
        skillId: "skill_hielo",
        skillName: "Hielo",
        category: "uso_hechizo_elemental_conocido",
        baseExp: 3,
        reason: "Uso de hechizo de hielo conocido.",
      },
    ],
    isRealSpell: true,
    isAdvanced: true,
    isOffensive: true,
    canUnlockAutomatically: false,
    publicUseRisk: "high",
    effectProfile: {
      effectType: "offense",
      damageType: "cold",
      targetType: "single_enemy",
      rangeBand: "short",
      combatUse: "offensive_simple",
      mechanicalNotes: ["Plantilla de dano frio menor.", "Congelacion de terreno u objetos requiere resolver efecto aparte."],
      narrationLimits: ["No congelar miembros o zonas sin backend.", "No crear hielo util gratis."],
    },
    safetyNotes: ["No practicar contra seres vivos fuera de combate formal.", "No desbloquear automaticamente."],
    tags: ["catalog", "locked", "spell_template", "offensive", "ice", "not_learned"],
  }),
  technique("technique_locked_earth_wind_push", {
    name: "Empuje de tierra y viento menor",
    disciplineId: "discipline_earth_wind",
    kind: "spell",
    status: "locked_template",
    description: "Plantilla bloqueada de empuje fisico menor mediante presion de aire/tierra.",
    defaultMinutes: 10,
    minMinutes: 10,
    maxMinutes: 10,
    activityCategory: "actividad_normal",
    difficulty: "advanced",
    mpCost: { fixed: 35, min: 35, max: 35, notes: "Coste mayor por control fisico del entorno." },
    requirements: {
      skills: [skill("skill_tierra_viento", 1), skill("skill_magia_ofensiva", 4), skill("skill_magia", 4), skill("skill_mana", 4)],
      knownTechniqueIds: [],
      notes: "Tierra/Viento requiere mas estructura que fuego/hielo/rayo basicos.",
    },
    expSuggestions: [
      {
        skillId: "skill_tierra_viento",
        skillName: "Tierra/Viento",
        category: "uso_hechizo_elemental_conocido",
        baseExp: 3,
        reason: "Uso de empuje elemental conocido.",
      },
    ],
    isRealSpell: true,
    isAdvanced: true,
    isOffensive: true,
    canUnlockAutomatically: false,
    publicUseRisk: "high",
    effectProfile: {
      effectType: "offense",
      damageType: "blunt",
      targetType: "single_enemy",
      rangeBand: "near",
      combatUse: "offensive_simple",
      mechanicalNotes: ["Plantilla de presion fisica menor.", "Derribos, empujes de posicion y terreno requieren resolucion futura."],
      narrationLimits: ["No mover rocas grandes.", "No derribar automaticamente sin backend."],
    },
    safetyNotes: ["No practicar cerca de gente u objetos fragiles.", "No desbloquear automaticamente."],
    tags: ["catalog", "locked", "spell_template", "offensive", "earth_wind", "not_learned"],
  }),
  technique("technique_locked_minor_ward", {
    name: "Resguardo menor",
    disciplineId: "discipline_defensive_magic",
    kind: "spell",
    status: "locked_template",
    description: "Plantilla bloqueada de proteccion basica. No reduce dano hasta que haya resolver defensivo formal.",
    defaultMinutes: 10,
    minMinutes: 10,
    maxMinutes: 10,
    activityCategory: "actividad_normal",
    difficulty: "advanced",
    mpCost: { fixed: 30, min: 30, max: 30, notes: "Coste de defensa principiante util." },
    requirements: {
      skills: [skill("skill_magia_defensiva", 1), skill("skill_magia", 3), skill("skill_mana", 3)],
      knownTechniqueIds: [],
      notes: "Requiere rama defensiva formal.",
    },
    expSuggestions: [
      {
        skillId: "skill_magia_defensiva",
        skillName: "Magia defensiva",
        category: "uso_hechizo_defensivo_conocido",
        baseExp: 3,
        reason: "Uso de resguardo defensivo conocido.",
      },
    ],
    isRealSpell: true,
    isAdvanced: true,
    isOffensive: false,
    canUnlockAutomatically: false,
    publicUseRisk: "medium",
    effectProfile: {
      effectType: "defense",
      damageType: "",
      targetType: "self",
      rangeBand: "none",
      combatUse: "defensive_future",
      mechanicalNotes: ["No soportado por use_magic ofensivo.", "Necesita resolver defensivo futuro para mitigar dano."],
      narrationLimits: ["No bloquear ataques por narracion.", "No crear barrera visible si no fue aplicado por backend."],
    },
    safetyNotes: ["No asumir mitigacion hasta que el backend la resuelva.", "No desbloquear automaticamente."],
    tags: ["catalog", "locked", "spell_template", "defense", "not_learned"],
  }),
  technique("technique_locked_minor_stabilization", {
    name: "Estabilizacion menor",
    disciplineId: "discipline_healing_magic",
    kind: "spell",
    status: "locked_template",
    description: "Plantilla bloqueada de estabilizacion curativa leve. No restaura vida ni cierra heridas gratis.",
    defaultMinutes: 10,
    minMinutes: 10,
    maxMinutes: 15,
    activityCategory: "actividad_normal",
    difficulty: "advanced",
    mpCost: { fixed: 40, min: 40, max: 40, notes: "Coste de magia curativa principiante regulada." },
    requirements: {
      skills: [skill("skill_magia_curativa", 1), skill("skill_magia", 5), skill("skill_mana", 5)],
      knownTechniqueIds: [],
      notes: "Curacion requiere control alto y responsabilidad medica.",
    },
    expSuggestions: [
      {
        skillId: "skill_magia_curativa",
        skillName: "Magia curativa",
        category: "uso_hechizo_curativo_conocido",
        baseExp: 2,
        reason: "Uso de estabilizacion curativa conocida.",
      },
    ],
    isRealSpell: true,
    isAdvanced: true,
    isOffensive: false,
    canUnlockAutomatically: false,
    publicUseRisk: "high",
    effectProfile: {
      effectType: "healing",
      damageType: "",
      targetType: "single_ally",
      rangeBand: "touch",
      combatUse: "healing_future",
      mechanicalNotes: ["No restaura vida.", "Solo debe estabilizar o apoyar tratamiento cuando exista resolver especifico."],
      narrationLimits: ["No curar instantaneamente.", "No cerrar fracturas, venenos o heridas graves por narracion."],
    },
    safetyNotes: ["Rama regulada.", "Requiere herida real y resolver de tratamiento futuro.", "No desbloquear automaticamente."],
    tags: ["catalog", "locked", "spell_template", "healing", "regulated", "not_learned"],
  }),
  technique("technique_locked_mental_presence_touch", {
    name: "Toque de presencia mental",
    disciplineId: "discipline_mental_magic",
    kind: "spell",
    status: "locked_template",
    description: "Plantilla bloqueada de contacto mental superficial y consentido. No lee secretos ni controla voluntad.",
    defaultMinutes: 10,
    minMinutes: 10,
    maxMinutes: 15,
    activityCategory: "actividad_normal",
    difficulty: "dangerous",
    mpCost: { fixed: 60, min: 60, max: 60, notes: "Coste alto por sensibilidad social y mental." },
    requirements: {
      skills: [skill("skill_magia_mental", 1), skill("skill_magia", 5, "Novato"), skill("skill_mana", 5, "Novato"), skill("skill_percepcion", 8)],
      knownTechniqueIds: [],
      notes: "Requiere rama mental y condiciones sociales claras.",
    },
    expSuggestions: [
      {
        skillId: "skill_magia_mental",
        skillName: "Magia mental",
        category: "uso_hechizo_mental_conocido",
        baseExp: 1,
        reason: "Uso de contacto mental conocido y consentido.",
      },
    ],
    isRealSpell: true,
    isAdvanced: true,
    isOffensive: false,
    canUnlockAutomatically: false,
    publicUseRisk: "high",
    effectProfile: {
      effectType: "mental",
      damageType: "",
      targetType: "single_ally",
      rangeBand: "touch",
      combatUse: "mental_future",
      mechanicalNotes: ["No soportado por combate ofensivo.", "Requiere consentimiento, contexto y consecuencias sociales."],
      narrationLimits: ["No leer pensamientos privados.", "No forzar emociones, recuerdos o decisiones."],
    },
    safetyNotes: ["Consentimiento y contexto obligatorio.", "No desbloquear automaticamente.", "Uso indebido debe generar riesgo social alto."],
    tags: ["catalog", "locked", "spell_template", "mental", "restricted", "not_learned"],
  }),
  technique("technique_locked_summoning_anchor_mark", {
    name: "Marca de anclaje de invocacion",
    disciplineId: "discipline_summoning_magic",
    kind: "spell",
    status: "locked_template",
    description: "Plantilla bloqueada de ancla ritual menor. No invoca criatura, objeto ni entidad por si sola.",
    defaultMinutes: 30,
    minMinutes: 30,
    maxMinutes: 60,
    activityCategory: "actividad_normal",
    difficulty: "dangerous",
    mpCost: { fixed: 120, min: 120, max: 120, notes: "Coste alto incluso para anclaje menor." },
    requirements: {
      skills: [skill("skill_magia_invocacion", 1), skill("skill_magia", 3, "Competente"), skill("skill_mana", 3, "Competente"), skill("skill_percepcion_magica", 8, "Novato")],
      knownTechniqueIds: [],
      notes: "Invocacion requiere control avanzado, ancla y cierre.",
    },
    expSuggestions: [
      {
        skillId: "skill_magia_invocacion",
        skillName: "Magia de invocacion",
        category: "ritual_invocacion_controlado",
        baseExp: 1,
        reason: "Uso de ancla ritual conocida.",
      },
    ],
    isRealSpell: true,
    isAdvanced: true,
    isOffensive: false,
    canUnlockAutomatically: false,
    publicUseRisk: "high",
    effectProfile: {
      effectType: "summoning",
      damageType: "",
      targetType: "ritual",
      rangeBand: "ritual",
      combatUse: "summoning_future",
      mechanicalNotes: ["No crea invocacion completa.", "Debe exigir origen, pacto/costo y cierre en fases futuras."],
      narrationLimits: ["No invocar aliados, armas ni criaturas.", "No abrir portales por narracion."],
    },
    safetyNotes: ["Rama avanzada fuera del juego temprano.", "No desbloquear automaticamente.", "Riesgo institucional alto."],
    tags: ["catalog", "locked", "spell_template", "summoning", "restricted", "not_learned"],
  }),
  technique("technique_locked_resistance_guard", {
    name: "Aguante arcano menor",
    disciplineId: "discipline_magic_resistance",
    kind: "spell",
    status: "locked_template",
    description: "Plantilla bloqueada de resistencia activa contra presion magica. No da inmunidad.",
    defaultMinutes: 10,
    minMinutes: 10,
    maxMinutes: 15,
    activityCategory: "actividad_normal",
    difficulty: "advanced",
    mpCost: { fixed: 35, min: 35, max: 35, notes: "Coste defensivo contra presion magica." },
    requirements: {
      skills: [skill("skill_resistencia_magica", 1), skill("skill_magia_defensiva", 2), skill("skill_mana", 3)],
      knownTechniqueIds: [],
      notes: "Requiere rama de resistencia magica formal.",
    },
    expSuggestions: [
      {
        skillId: "skill_resistencia_magica",
        skillName: "Resistencia magica",
        category: "uso_resistencia_magica_conocida",
        baseExp: 3,
        reason: "Uso de aguante arcano conocido.",
      },
    ],
    isRealSpell: true,
    isAdvanced: true,
    isOffensive: false,
    canUnlockAutomatically: false,
    publicUseRisk: "medium",
    effectProfile: {
      effectType: "resistance",
      damageType: "",
      targetType: "self",
      rangeBand: "none",
      combatUse: "resistance_future",
      mechanicalNotes: ["No soportado por combate ofensivo.", "Mitigacion requiere resolver especifico futuro."],
      narrationLimits: ["No negar hechizos enemigos automaticamente.", "No convertir en inmunidad."],
    },
    safetyNotes: ["No asumir mitigacion sin backend.", "No desbloquear automaticamente."],
    tags: ["catalog", "locked", "spell_template", "resistance", "not_learned"],
  }),
];

async function assertTechniqueDisciplinesExist() {
  const disciplineIds = new Set(disciplines.map((entry) => entry.disciplineId));
  const missing = techniques
    .map((entry) => entry.disciplineId)
    .filter((disciplineId) => !disciplineIds.has(disciplineId));

  if (missing.length > 0) {
    throw new Error(`Technique discipline refs not in seed: ${Array.from(new Set(missing)).join(", ")}`);
  }
}

async function seedMagicBasics() {
  await connectDB();

  if (mongoose.connection.readyState !== 1) {
    throw new Error("MONGODB_URI is required to seed magic basics.");
  }

  await assertTechniqueDisciplinesExist();

  await MagicDiscipline.bulkWrite(
    disciplines.map((entry) => ({
      updateOne: {
        filter: { disciplineId: entry.disciplineId },
        update: { $set: entry },
        upsert: true,
      },
    })),
    { ordered: false }
  );

  await MagicTechnique.bulkWrite(
    techniques.map((entry) => ({
      updateOne: {
        filter: { techniqueId: entry.techniqueId },
        update: { $set: entry },
        upsert: true,
      },
    })),
    { ordered: false }
  );

  const [disciplineCount, techniqueCount] = await Promise.all([
    MagicDiscipline.countDocuments({ source: SOURCE, tags: { $all: MARKER_TAGS } }),
    MagicTechnique.countDocuments({ source: SOURCE, tags: { $all: MARKER_TAGS } }),
  ]);

  console.log("Magic basics seed completed.");
  console.log(`Expected G11 disciplines in seed: ${disciplines.length}`);
  console.log(`Expected G11 techniques in seed: ${techniques.length}`);
  console.log(`MongoDB G11 disciplines found: ${disciplineCount}`);
  console.log(`MongoDB G11 techniques found: ${techniqueCount}`);

  await mongoose.disconnect();
}

if (require.main === module) {
  seedMagicBasics().catch(async (error) => {
    console.error("Error seeding magic basics:", error.message);
    await mongoose.disconnect();
    process.exit(1);
  });
}

module.exports = {
  MARKER_TAGS,
  SOURCE,
  disciplines,
  techniques,
  seedMagicBasics,
};
